# DO NOT EDIT — generated by purecdp._generator (devtools-protocol 3bd8f01934b5)
'''Generated CDP bindings, protocol version 1.3.

Domain modules load lazily on first attribute access (PEP 562).
Event classes register with purecdp._shared only when their module is
imported; call load_all() to populate the full event registry, or
import_domain() to resolve a single domain by its CDP name.
'''

from __future__ import annotations

import importlib
import typing

__all__ = [
    'accessibility',
    'ads',
    'animation',
    'audits',
    'autofill',
    'background_service',
    'bluetooth_emulation',
    'browser',
    'cache_storage',
    'cast',
    'console',
    'crash_report_context',
    'css',
    'debugger',
    'device_access',
    'device_orientation',
    'digital_credentials',
    'dom',
    'dom_debugger',
    'dom_snapshot',
    'dom_storage',
    'emulation',
    'event_breakpoints',
    'extensions',
    'fed_cm',
    'fetch',
    'file_system',
    'headless_experimental',
    'heap_profiler',
    'indexed_db',
    'input',
    'inspector',
    'io',
    'layer_tree',
    'log',
    'media',
    'memory',
    'network',
    'overlay',
    'page',
    'performance',
    'performance_timeline',
    'preload',
    'profiler',
    'pwa',
    'runtime',
    'schema',
    'security',
    'service_worker',
    'smart_card_emulation',
    'storage',
    'system_info',
    'target',
    'tethering',
    'tracing',
    'web_audio',
    'web_authn',
    'web_mcp',
]

#: CDP domain name -> module name in this package.
DOMAIN_MODULES: dict[str, str] = {
    'Accessibility': 'accessibility',
    'Ads': 'ads',
    'Animation': 'animation',
    'Audits': 'audits',
    'Autofill': 'autofill',
    'BackgroundService': 'background_service',
    'BluetoothEmulation': 'bluetooth_emulation',
    'Browser': 'browser',
    'CSS': 'css',
    'CacheStorage': 'cache_storage',
    'Cast': 'cast',
    'Console': 'console',
    'CrashReportContext': 'crash_report_context',
    'DOM': 'dom',
    'DOMDebugger': 'dom_debugger',
    'DOMSnapshot': 'dom_snapshot',
    'DOMStorage': 'dom_storage',
    'Debugger': 'debugger',
    'DeviceAccess': 'device_access',
    'DeviceOrientation': 'device_orientation',
    'DigitalCredentials': 'digital_credentials',
    'Emulation': 'emulation',
    'EventBreakpoints': 'event_breakpoints',
    'Extensions': 'extensions',
    'FedCm': 'fed_cm',
    'Fetch': 'fetch',
    'FileSystem': 'file_system',
    'HeadlessExperimental': 'headless_experimental',
    'HeapProfiler': 'heap_profiler',
    'IO': 'io',
    'IndexedDB': 'indexed_db',
    'Input': 'input',
    'Inspector': 'inspector',
    'LayerTree': 'layer_tree',
    'Log': 'log',
    'Media': 'media',
    'Memory': 'memory',
    'Network': 'network',
    'Overlay': 'overlay',
    'PWA': 'pwa',
    'Page': 'page',
    'Performance': 'performance',
    'PerformanceTimeline': 'performance_timeline',
    'Preload': 'preload',
    'Profiler': 'profiler',
    'Runtime': 'runtime',
    'Schema': 'schema',
    'Security': 'security',
    'ServiceWorker': 'service_worker',
    'SmartCardEmulation': 'smart_card_emulation',
    'Storage': 'storage',
    'SystemInfo': 'system_info',
    'Target': 'target',
    'Tethering': 'tethering',
    'Tracing': 'tracing',
    'WebAudio': 'web_audio',
    'WebAuthn': 'web_authn',
    'WebMCP': 'web_mcp',
}


def import_domain(domain: str) -> typing.Any:
    '''Import and return the module for a CDP domain name (e.g. 'DOM').

    Raises KeyError for domains not in the pinned spec.
    '''
    return importlib.import_module('.' + DOMAIN_MODULES[domain], __name__)


def __getattr__(name: str) -> typing.Any:
    if name in __all__:
        return importlib.import_module('.' + name, __name__)
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')


def load_all() -> None:
    '''Import every domain module (fully populates the event registry).'''
    for name in __all__:
        importlib.import_module('.' + name, __name__)
