# DO NOT EDIT — generated by purecdp._generator from Ads (devtools-protocol 3bd8f01934b5)
'''CDP domain: Ads.

A domain for ad-related metrics and data.

**EXPERIMENTAL**
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class

from . import page


@dataclass(slots=True)
class AdFrameData:
    '''Ad frame data.'''
    #: The DevTools frame token.
    frame_id: page.FrameId
    #: The network bytes of the frame.
    network_bytes: float
    #: The CPU time of the frame, in milliseconds.
    cpu_time: float
    #: *(Optional)* The initial origin of the frame. To minimize the payload size, this is only sent once per frame.
    initial_origin: str | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['frameId'] = self.frame_id.to_json()
        json['networkBytes'] = self.network_bytes
        json['cpuTime'] = self.cpu_time
        if self.initial_origin is not None:
            json['initialOrigin'] = self.initial_origin
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AdFrameData:
        return cls(
            frame_id=page.FrameId.from_json(json['frameId']),
            network_bytes=float(json['networkBytes']),
            cpu_time=float(json['cpuTime']),
            initial_origin=json['initialOrigin'] if json.get('initialOrigin') is not None else None,
        )


@dataclass(slots=True)
class AdMetrics:
    '''Ad metrics for a page.'''
    #: The viewport ad density by area, represented as a percentage (an integer between 0 and 100).
    viewport_ad_density_by_area: int
    #: The time-weighted average of the viewport ad density by area, measured across the duration of the page.
    average_viewport_ad_density_by_area: float
    #: The number of ads currently visible within the viewport.
    viewport_ad_count: int
    #: The time-weighted average of the viewport ad count, measured across the duration of the page.
    average_viewport_ad_count: float
    #: The total ad CPU usage, in milliseconds.
    total_ad_cpu_time: float
    #: The total ad network bytes.
    total_ad_network_bytes: float
    #: The list of ad frames that have been updated since the last event.
    update_ad_frames: list[AdFrameData]
    #: The list of ad frame IDs that have been removed since the last event.
    remove_ad_frames: list[page.FrameId]

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['viewportAdDensityByArea'] = self.viewport_ad_density_by_area
        json['averageViewportAdDensityByArea'] = self.average_viewport_ad_density_by_area
        json['viewportAdCount'] = self.viewport_ad_count
        json['averageViewportAdCount'] = self.average_viewport_ad_count
        json['totalAdCpuTime'] = self.total_ad_cpu_time
        json['totalAdNetworkBytes'] = self.total_ad_network_bytes
        json['updateAdFrames'] = [i.to_json() for i in self.update_ad_frames]
        json['removeAdFrames'] = [i.to_json() for i in self.remove_ad_frames]
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AdMetrics:
        return cls(
            viewport_ad_density_by_area=json['viewportAdDensityByArea'],
            average_viewport_ad_density_by_area=float(json['averageViewportAdDensityByArea']),
            viewport_ad_count=json['viewportAdCount'],
            average_viewport_ad_count=float(json['averageViewportAdCount']),
            total_ad_cpu_time=float(json['totalAdCpuTime']),
            total_ad_network_bytes=float(json['totalAdNetworkBytes']),
            update_ad_frames=[AdFrameData.from_json(i) for i in json['updateAdFrames']],
            remove_ad_frames=[page.FrameId.from_json(i) for i in json['removeAdFrames']],
        )


def get_ad_metrics() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, AdMetrics]:
    '''Retrieves ad metrics for the current page.

    :returns:
    '''
    json = yield {'method': 'Ads.getAdMetrics'}
    return AdMetrics.from_json(json['metrics'])
