# DO NOT EDIT — generated by purecdp._generator from Browser (devtools-protocol 3bd8f01934b5)
'''CDP domain: Browser.

The Browser domain defines methods and events for browser managing.
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class

from . import page, target


class BrowserContextID(str):
    '''**EXPERIMENTAL**'''
    def to_json(self) -> str:
        return str(self)

    @classmethod
    def from_json(cls, json: str) -> BrowserContextID:
        return cls(json)

    def __repr__(self) -> str:
        return f'BrowserContextID({str.__repr__(self)})'


class WindowID(int):
    '''**EXPERIMENTAL**'''
    def to_json(self) -> int:
        return int(self)

    @classmethod
    def from_json(cls, json: int) -> WindowID:
        return cls(json)

    def __repr__(self) -> str:
        return f'WindowID({int.__repr__(self)})'


class WindowState(enum.StrEnum):
    '''The state of the browser window.

    **EXPERIMENTAL**
    '''
    NORMAL = 'normal'
    MINIMIZED = 'minimized'
    MAXIMIZED = 'maximized'
    FULLSCREEN = 'fullscreen'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> WindowState:
        return cls(json)


@dataclass(slots=True)
class Bounds:
    '''Browser window bounds information

    **EXPERIMENTAL**
    '''
    #: *(Optional)* The offset from the left edge of the screen to the window in pixels.
    left: int | None = None
    #: *(Optional)* The offset from the top edge of the screen to the window in pixels.
    top: int | None = None
    #: *(Optional)* The window width in pixels.
    width: int | None = None
    #: *(Optional)* The window height in pixels.
    height: int | None = None
    #: *(Optional)* The window state. Default to normal.
    window_state: WindowState | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        if self.left is not None:
            json['left'] = self.left
        if self.top is not None:
            json['top'] = self.top
        if self.width is not None:
            json['width'] = self.width
        if self.height is not None:
            json['height'] = self.height
        if self.window_state is not None:
            json['windowState'] = self.window_state.to_json()
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Bounds:
        return cls(
            left=json['left'] if json.get('left') is not None else None,
            top=json['top'] if json.get('top') is not None else None,
            width=json['width'] if json.get('width') is not None else None,
            height=json['height'] if json.get('height') is not None else None,
            window_state=WindowState.from_json(json['windowState']) if json.get('windowState') is not None else None,
        )


class PermissionType(enum.StrEnum):
    '''**EXPERIMENTAL**'''
    AR = 'ar'
    AUDIO_CAPTURE = 'audioCapture'
    AUTOMATIC_FULLSCREEN = 'automaticFullscreen'
    BACKGROUND_FETCH = 'backgroundFetch'
    BACKGROUND_SYNC = 'backgroundSync'
    CAMERA_PAN_TILT_ZOOM = 'cameraPanTiltZoom'
    CAPTURED_SURFACE_CONTROL = 'capturedSurfaceControl'
    CLIPBOARD_READ_WRITE = 'clipboardReadWrite'
    CLIPBOARD_SANITIZED_WRITE = 'clipboardSanitizedWrite'
    DISPLAY_CAPTURE = 'displayCapture'
    DURABLE_STORAGE = 'durableStorage'
    GEOLOCATION = 'geolocation'
    HAND_TRACKING = 'handTracking'
    IDLE_DETECTION = 'idleDetection'
    KEYBOARD_LOCK = 'keyboardLock'
    LOCAL_FONTS = 'localFonts'
    LOCAL_NETWORK = 'localNetwork'
    LOCAL_NETWORK_ACCESS = 'localNetworkAccess'
    LOOPBACK_NETWORK = 'loopbackNetwork'
    MIDI = 'midi'
    MIDI_SYSEX = 'midiSysex'
    NFC = 'nfc'
    NOTIFICATIONS = 'notifications'
    PAYMENT_HANDLER = 'paymentHandler'
    PERIODIC_BACKGROUND_SYNC = 'periodicBackgroundSync'
    POINTER_LOCK = 'pointerLock'
    PROTECTED_MEDIA_IDENTIFIER = 'protectedMediaIdentifier'
    SENSORS = 'sensors'
    SMART_CARD = 'smartCard'
    SPEAKER_SELECTION = 'speakerSelection'
    STORAGE_ACCESS = 'storageAccess'
    TOP_LEVEL_STORAGE_ACCESS = 'topLevelStorageAccess'
    VIDEO_CAPTURE = 'videoCapture'
    VR = 'vr'
    WAKE_LOCK_SCREEN = 'wakeLockScreen'
    WAKE_LOCK_SYSTEM = 'wakeLockSystem'
    WEB_APP_INSTALLATION = 'webAppInstallation'
    WEB_PRINTING = 'webPrinting'
    WINDOW_MANAGEMENT = 'windowManagement'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> PermissionType:
        return cls(json)


class PermissionSetting(enum.StrEnum):
    '''**EXPERIMENTAL**'''
    GRANTED = 'granted'
    DENIED = 'denied'
    PROMPT = 'prompt'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> PermissionSetting:
        return cls(json)


@dataclass(slots=True)
class PermissionDescriptor:
    '''Definition of PermissionDescriptor defined in the Permissions API:
    https://w3c.github.io/permissions/#dom-permissiondescriptor.

    **EXPERIMENTAL**
    '''
    #: Name of permission. See https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/permissions/permission_descriptor.idl for valid permission names.
    name: str
    #: *(Optional)* For "midi" permission, may also specify sysex control.
    sysex: bool | None = None
    #: *(Optional)* For "push" permission, may specify userVisibleOnly. Note that userVisibleOnly = true is the only currently supported type.
    user_visible_only: bool | None = None
    #: *(Optional)* For "clipboard" permission, may specify allowWithoutSanitization.
    allow_without_sanitization: bool | None = None
    #: *(Optional)* For "fullscreen" permission, must specify allowWithoutGesture:true.
    allow_without_gesture: bool | None = None
    #: *(Optional)* For "camera" permission, may specify panTiltZoom.
    pan_tilt_zoom: bool | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['name'] = self.name
        if self.sysex is not None:
            json['sysex'] = self.sysex
        if self.user_visible_only is not None:
            json['userVisibleOnly'] = self.user_visible_only
        if self.allow_without_sanitization is not None:
            json['allowWithoutSanitization'] = self.allow_without_sanitization
        if self.allow_without_gesture is not None:
            json['allowWithoutGesture'] = self.allow_without_gesture
        if self.pan_tilt_zoom is not None:
            json['panTiltZoom'] = self.pan_tilt_zoom
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PermissionDescriptor:
        return cls(
            name=json['name'],
            sysex=json['sysex'] if json.get('sysex') is not None else None,
            user_visible_only=json['userVisibleOnly'] if json.get('userVisibleOnly') is not None else None,
            allow_without_sanitization=json['allowWithoutSanitization'] if json.get('allowWithoutSanitization') is not None else None,
            allow_without_gesture=json['allowWithoutGesture'] if json.get('allowWithoutGesture') is not None else None,
            pan_tilt_zoom=json['panTiltZoom'] if json.get('panTiltZoom') is not None else None,
        )


class BrowserCommandId(enum.StrEnum):
    '''Browser command ids used by executeBrowserCommand.

    **EXPERIMENTAL**
    '''
    OPEN_TAB_SEARCH = 'openTabSearch'
    CLOSE_TAB_SEARCH = 'closeTabSearch'
    OPEN_GLIC = 'openGlic'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> BrowserCommandId:
        return cls(json)


@dataclass(slots=True)
class Bucket:
    '''Chrome histogram bucket.

    **EXPERIMENTAL**
    '''
    #: Minimum value (inclusive).
    low: int
    #: Maximum value (exclusive).
    high: int
    #: Number of samples.
    count: int

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['low'] = self.low
        json['high'] = self.high
        json['count'] = self.count
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Bucket:
        return cls(
            low=json['low'],
            high=json['high'],
            count=json['count'],
        )


@dataclass(slots=True)
class Histogram:
    '''Chrome histogram.

    **EXPERIMENTAL**
    '''
    #: Name.
    name: str
    #: Sum of sample values.
    sum: int
    #: Total number of samples.
    count: int
    #: Buckets.
    buckets: list[Bucket]

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['name'] = self.name
        json['sum'] = self.sum
        json['count'] = self.count
        json['buckets'] = [i.to_json() for i in self.buckets]
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Histogram:
        return cls(
            name=json['name'],
            sum=json['sum'],
            count=json['count'],
            buckets=[Bucket.from_json(i) for i in json['buckets']],
        )


def set_permission(
        permission: PermissionDescriptor,
        setting: PermissionSetting,
        origin: str | None = None,
        embedded_origin: str | None = None,
        browser_context_id: BrowserContextID | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Set permission settings for given embedding and embedded origins.

    **EXPERIMENTAL**

    :param permission: Descriptor of permission to override.
    :param setting: Setting of the permission.
    :param origin: *(Optional)* Embedding origin the permission applies to, all origins if not specified.
    :param embedded_origin: *(Optional)* Embedded origin the permission applies to. It is ignored unless the embedding origin is present and valid. If the embedding origin is provided but the embedded origin isn't, the embedding origin is used as the embedded origin.
    :param browser_context_id: *(Optional)* Context to override. When omitted, default browser context is used.
    '''
    params: T_JSON_DICT = {}
    params['permission'] = permission.to_json()
    params['setting'] = setting.to_json()
    if origin is not None:
        params['origin'] = origin
    if embedded_origin is not None:
        params['embeddedOrigin'] = embedded_origin
    if browser_context_id is not None:
        params['browserContextId'] = browser_context_id.to_json()
    yield {'method': 'Browser.setPermission', 'params': params}


def grant_permissions(
        permissions: list[PermissionType],
        origin: str | None = None,
        browser_context_id: BrowserContextID | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Grant specific permissions to the given origin and reject all others. Deprecated. Use
    setPermission instead.

    **EXPERIMENTAL** **DEPRECATED**

    :param permissions:
    :param origin: *(Optional)* Origin the permission applies to, all origins if not specified.
    :param browser_context_id: *(Optional)* BrowserContext to override permissions. When omitted, default browser context is used.
    '''
    params: T_JSON_DICT = {}
    params['permissions'] = [i.to_json() for i in permissions]
    if origin is not None:
        params['origin'] = origin
    if browser_context_id is not None:
        params['browserContextId'] = browser_context_id.to_json()
    yield {'method': 'Browser.grantPermissions', 'params': params}


def reset_permissions(
        browser_context_id: BrowserContextID | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Reset all permission management for all origins.

    :param browser_context_id: *(Optional)* BrowserContext to reset permissions. When omitted, default browser context is used.
    '''
    params: T_JSON_DICT = {}
    if browser_context_id is not None:
        params['browserContextId'] = browser_context_id.to_json()
    yield {'method': 'Browser.resetPermissions', 'params': params}


def set_download_behavior(
        behavior: str,
        browser_context_id: BrowserContextID | None = None,
        download_path: str | None = None,
        events_enabled: bool | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Set the behavior when downloading a file.

    **EXPERIMENTAL**

    :param behavior: Whether to allow all or deny all download requests, or use default Chrome behavior if available (otherwise deny). |allowAndName| allows download and names files according to their download guids. Allowed values: deny, allow, allowAndName, default
    :param browser_context_id: *(Optional)* BrowserContext to set download behavior. When omitted, default browser context is used.
    :param download_path: *(Optional)* The default path to save downloaded files to. This is required if behavior is set to 'allow' or 'allowAndName'.
    :param events_enabled: *(Optional)* Whether to emit download events (defaults to false).
    '''
    params: T_JSON_DICT = {}
    params['behavior'] = behavior
    if browser_context_id is not None:
        params['browserContextId'] = browser_context_id.to_json()
    if download_path is not None:
        params['downloadPath'] = download_path
    if events_enabled is not None:
        params['eventsEnabled'] = events_enabled
    yield {'method': 'Browser.setDownloadBehavior', 'params': params}


def cancel_download(
        guid: str,
        browser_context_id: BrowserContextID | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Cancel a download if in progress

    **EXPERIMENTAL**

    :param guid: Global unique identifier of the download.
    :param browser_context_id: *(Optional)* BrowserContext to perform the action in. When omitted, default browser context is used.
    '''
    params: T_JSON_DICT = {}
    params['guid'] = guid
    if browser_context_id is not None:
        params['browserContextId'] = browser_context_id.to_json()
    yield {'method': 'Browser.cancelDownload', 'params': params}


def close() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Close browser gracefully.'''
    yield {'method': 'Browser.close'}


def crash() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Crashes browser on the main thread.

    **EXPERIMENTAL**
    '''
    yield {'method': 'Browser.crash'}


def crash_gpu_process() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Crashes GPU process.

    **EXPERIMENTAL**
    '''
    yield {'method': 'Browser.crashGpuProcess'}


def get_version() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, tuple[str, str, str, str, str]]:
    '''Returns version information.

    :returns: A tuple with the following items:
        0. **protocolVersion** — Protocol version.
        1. **product** — Product name.
        2. **revision** — Product revision.
        3. **userAgent** — User-Agent.
        4. **jsVersion** — V8 version.
    '''
    json = yield {'method': 'Browser.getVersion'}
    return (
        json['protocolVersion'],
        json['product'],
        json['revision'],
        json['userAgent'],
        json['jsVersion'],
    )


def get_browser_command_line() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[str]]:
    '''Returns the command line switches for the browser process if, and only if
    --enable-automation is on the commandline.

    **EXPERIMENTAL**

    :returns: Commandline parameters
    '''
    json = yield {'method': 'Browser.getBrowserCommandLine'}
    return list(json['arguments'])


def get_histograms(
        query: str | None = None,
        delta: bool | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[Histogram]]:
    '''Get Chrome histograms.

    **EXPERIMENTAL**

    :param query: *(Optional)* Requested substring in name. Only histograms which have query as a substring in their name are extracted. An empty or absent query returns all histograms.
    :param delta: *(Optional)* If true, retrieve delta since last delta call.
    :returns: Histograms.
    '''
    params: T_JSON_DICT = {}
    if query is not None:
        params['query'] = query
    if delta is not None:
        params['delta'] = delta
    json = yield {'method': 'Browser.getHistograms', 'params': params}
    return [Histogram.from_json(i) for i in json['histograms']]


def get_histogram(
        name: str,
        delta: bool | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, Histogram]:
    '''Get a Chrome histogram by name.

    **EXPERIMENTAL**

    :param name: Requested histogram name.
    :param delta: *(Optional)* If true, retrieve delta since last delta call.
    :returns: Histogram.
    '''
    params: T_JSON_DICT = {}
    params['name'] = name
    if delta is not None:
        params['delta'] = delta
    json = yield {'method': 'Browser.getHistogram', 'params': params}
    return Histogram.from_json(json['histogram'])


def get_window_bounds(window_id: WindowID) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, Bounds]:
    '''Get position and size of the browser window.

    **EXPERIMENTAL**

    :param window_id: Browser window id.
    :returns: Bounds information of the window. When window state is 'minimized', the restored window position and size are returned.
    '''
    params: T_JSON_DICT = {}
    params['windowId'] = window_id.to_json()
    json = yield {'method': 'Browser.getWindowBounds', 'params': params}
    return Bounds.from_json(json['bounds'])


def get_window_for_target(
        target_id: target.TargetID | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, tuple[WindowID, Bounds]]:
    '''Get the browser window that contains the devtools target.

    **EXPERIMENTAL**

    :param target_id: *(Optional)* Devtools agent host id. If called as a part of the session, associated targetId is used.
    :returns: A tuple with the following items:
        0. **windowId** — Browser window id.
        1. **bounds** — Bounds information of the window. When window state is 'minimized', the restored window position and size are returned.
    '''
    params: T_JSON_DICT = {}
    if target_id is not None:
        params['targetId'] = target_id.to_json()
    json = yield {'method': 'Browser.getWindowForTarget', 'params': params}
    return (
        WindowID.from_json(json['windowId']),
        Bounds.from_json(json['bounds']),
    )


def set_window_bounds(
        window_id: WindowID,
        bounds: Bounds,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Set position and/or size of the browser window.

    **EXPERIMENTAL**

    :param window_id: Browser window id.
    :param bounds: New window bounds. The 'minimized', 'maximized' and 'fullscreen' states cannot be combined with 'left', 'top', 'width' or 'height'. Leaves unspecified fields unchanged.
    '''
    params: T_JSON_DICT = {}
    params['windowId'] = window_id.to_json()
    params['bounds'] = bounds.to_json()
    yield {'method': 'Browser.setWindowBounds', 'params': params}


def set_contents_size(
        window_id: WindowID,
        width: int | None = None,
        height: int | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Set size of the browser contents resizing browser window as necessary.

    **EXPERIMENTAL**

    :param window_id: Browser window id.
    :param width: *(Optional)* The window contents width in DIP. Assumes current width if omitted. Must be specified if 'height' is omitted.
    :param height: *(Optional)* The window contents height in DIP. Assumes current height if omitted. Must be specified if 'width' is omitted.
    '''
    params: T_JSON_DICT = {}
    params['windowId'] = window_id.to_json()
    if width is not None:
        params['width'] = width
    if height is not None:
        params['height'] = height
    yield {'method': 'Browser.setContentsSize', 'params': params}


def set_dock_tile(
        badge_label: str | None = None,
        image: str | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Set dock tile details, platform-specific.

    **EXPERIMENTAL**

    :param badge_label: *(Optional)*
    :param image: *(Optional)* Png encoded image. (Encoded as a base64 string when passed over JSON)
    '''
    params: T_JSON_DICT = {}
    if badge_label is not None:
        params['badgeLabel'] = badge_label
    if image is not None:
        params['image'] = image
    yield {'method': 'Browser.setDockTile', 'params': params}


def execute_browser_command(
        command_id: BrowserCommandId,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Invoke custom browser commands used by telemetry.

    **EXPERIMENTAL**

    :param command_id:
    '''
    params: T_JSON_DICT = {}
    params['commandId'] = command_id.to_json()
    yield {'method': 'Browser.executeBrowserCommand', 'params': params}


def add_privacy_sandbox_enrollment_override(
        url: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Allows a site to use privacy sandbox features that require enrollment
    without the site actually being enrolled. Only supported on page targets.

    :param url:
    '''
    params: T_JSON_DICT = {}
    params['url'] = url
    yield {'method': 'Browser.addPrivacySandboxEnrollmentOverride', 'params': params}


@event_class('Browser.downloadWillBegin')
@dataclass(slots=True)
class DownloadWillBegin:
    '''Fired when page is about to start a download.

    **EXPERIMENTAL**
    '''
    #: Id of the frame that caused the download to begin.
    frame_id: page.FrameId
    #: Global unique identifier of the download.
    guid: str
    #: URL of the resource being downloaded.
    url: str
    #: Suggested file name of the resource (the actual name of the file saved on disk may differ).
    suggested_filename: str

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DownloadWillBegin:
        return cls(
            frame_id=page.FrameId.from_json(json['frameId']),
            guid=json['guid'],
            url=json['url'],
            suggested_filename=json['suggestedFilename'],
        )


@event_class('Browser.downloadProgress')
@dataclass(slots=True)
class DownloadProgress:
    '''Fired when download makes progress. Last call has |done| == true.

    **EXPERIMENTAL**
    '''
    #: Global unique identifier of the download.
    guid: str
    #: Total expected bytes to download.
    total_bytes: float
    #: Total bytes received.
    received_bytes: float
    #: Download status. Allowed values: inProgress, completed, canceled
    state: str
    #: *(Optional)* If download is "completed", provides the path of the downloaded file. Depending on the platform, it is not guaranteed to be set, nor the file is guaranteed to exist. *(EXPERIMENTAL)*
    file_path: str | None = None

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DownloadProgress:
        return cls(
            guid=json['guid'],
            total_bytes=float(json['totalBytes']),
            received_bytes=float(json['receivedBytes']),
            state=json['state'],
            file_path=json['filePath'] if json.get('filePath') is not None else None,
        )
