# DO NOT EDIT — generated by purecdp._generator from Console (devtools-protocol 3bd8f01934b5)
'''CDP domain: Console.

This domain is deprecated - use Runtime or Log instead.

**DEPRECATED**
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class


@dataclass(slots=True)
class ConsoleMessage:
    '''Console message.'''
    #: Message source. Allowed values: xml, javascript, network, console-api, storage, appcache, rendering, security, other, deprecation, worker
    source: str
    #: Message severity. Allowed values: log, warning, error, debug, info
    level: str
    #: Message text.
    text: str
    #: *(Optional)* URL of the message origin.
    url: str | None = None
    #: *(Optional)* Line number in the resource that generated this message (1-based).
    line: int | None = None
    #: *(Optional)* Column number in the resource that generated this message (1-based).
    column: int | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['source'] = self.source
        json['level'] = self.level
        json['text'] = self.text
        if self.url is not None:
            json['url'] = self.url
        if self.line is not None:
            json['line'] = self.line
        if self.column is not None:
            json['column'] = self.column
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ConsoleMessage:
        return cls(
            source=json['source'],
            level=json['level'],
            text=json['text'],
            url=json['url'] if json.get('url') is not None else None,
            line=json['line'] if json.get('line') is not None else None,
            column=json['column'] if json.get('column') is not None else None,
        )


def clear_messages() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Does nothing.'''
    yield {'method': 'Console.clearMessages'}


def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Disables console domain, prevents further console messages from being reported to the client.'''
    yield {'method': 'Console.disable'}


def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Enables console domain, sends the messages collected so far to the client by means of the
    `messageAdded` notification.
    '''
    yield {'method': 'Console.enable'}


@event_class('Console.messageAdded')
@dataclass(slots=True)
class MessageAdded:
    '''Issued when new console message is added.'''
    #: Console message that has been added.
    message: ConsoleMessage

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> MessageAdded:
        return cls(
            message=ConsoleMessage.from_json(json['message']),
        )
