# DO NOT EDIT — generated by purecdp._generator from CrashReportContext (devtools-protocol 3bd8f01934b5)
'''CDP domain: CrashReportContext.

This domain exposes the current state of the CrashReportContext API.

**EXPERIMENTAL**
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class

from . import page


@dataclass(slots=True)
class CrashReportContextEntry:
    '''Key-value pair in CrashReportContext.'''
    key: str
    value: str
    #: The ID of the frame where the key-value pair was set.
    frame_id: page.FrameId

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['key'] = self.key
        json['value'] = self.value
        json['frameId'] = self.frame_id.to_json()
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CrashReportContextEntry:
        return cls(
            key=json['key'],
            value=json['value'],
            frame_id=page.FrameId.from_json(json['frameId']),
        )


def get_entries() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[CrashReportContextEntry]]:
    '''Returns all entries in the CrashReportContext across all frames in the page.

    :returns:
    '''
    json = yield {'method': 'CrashReportContext.getEntries'}
    return [CrashReportContextEntry.from_json(i) for i in json['entries']]
