# DO NOT EDIT — generated by purecdp._generator from DeviceOrientation (devtools-protocol 3bd8f01934b5)
'''CDP domain: DeviceOrientation.

**EXPERIMENTAL**
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class


def clear_device_orientation_override() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Clears the overridden Device Orientation.'''
    yield {'method': 'DeviceOrientation.clearDeviceOrientationOverride'}


def set_device_orientation_override(
        alpha: float,
        beta: float,
        gamma: float,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Overrides the Device Orientation.

    :param alpha: Mock alpha
    :param beta: Mock beta
    :param gamma: Mock gamma
    '''
    params: T_JSON_DICT = {}
    params['alpha'] = alpha
    params['beta'] = beta
    params['gamma'] = gamma
    yield {'method': 'DeviceOrientation.setDeviceOrientationOverride', 'params': params}
