# DO NOT EDIT — generated by purecdp._generator from DeviceAccess (devtools-protocol 3bd8f01934b5)
'''CDP domain: DeviceAccess.

**EXPERIMENTAL**
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class


class RequestId(str):
    '''Device request id.'''
    def to_json(self) -> str:
        return str(self)

    @classmethod
    def from_json(cls, json: str) -> RequestId:
        return cls(json)

    def __repr__(self) -> str:
        return f'RequestId({str.__repr__(self)})'


class DeviceId(str):
    '''A device id.'''
    def to_json(self) -> str:
        return str(self)

    @classmethod
    def from_json(cls, json: str) -> DeviceId:
        return cls(json)

    def __repr__(self) -> str:
        return f'DeviceId({str.__repr__(self)})'


@dataclass(slots=True)
class PromptDevice:
    '''Device information displayed in a user prompt to select a device.'''
    id: DeviceId
    #: Display name as it appears in a device request user prompt.
    name: str

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['id'] = self.id.to_json()
        json['name'] = self.name
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PromptDevice:
        return cls(
            id=DeviceId.from_json(json['id']),
            name=json['name'],
        )


def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Enable events in this domain.'''
    yield {'method': 'DeviceAccess.enable'}


def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Disable events in this domain.'''
    yield {'method': 'DeviceAccess.disable'}


def select_prompt(
        id: RequestId,
        device_id: DeviceId,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Select a device in response to a DeviceAccess.deviceRequestPrompted event.

    :param id:
    :param device_id:
    '''
    params: T_JSON_DICT = {}
    params['id'] = id.to_json()
    params['deviceId'] = device_id.to_json()
    yield {'method': 'DeviceAccess.selectPrompt', 'params': params}


def cancel_prompt(id: RequestId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Cancel a prompt in response to a DeviceAccess.deviceRequestPrompted event.

    :param id:
    '''
    params: T_JSON_DICT = {}
    params['id'] = id.to_json()
    yield {'method': 'DeviceAccess.cancelPrompt', 'params': params}


@event_class('DeviceAccess.deviceRequestPrompted')
@dataclass(slots=True)
class DeviceRequestPrompted:
    '''A device request opened a user prompt to select a device. Respond with the
    selectPrompt or cancelPrompt command.
    '''
    id: RequestId
    devices: list[PromptDevice]

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DeviceRequestPrompted:
        return cls(
            id=RequestId.from_json(json['id']),
            devices=[PromptDevice.from_json(i) for i in json['devices']],
        )
