# DO NOT EDIT — generated by purecdp._generator from DigitalCredentials (devtools-protocol 3bd8f01934b5)
'''CDP domain: DigitalCredentials.

This domain allows interacting with the Digital Credentials API for automation.

**EXPERIMENTAL**
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class

from . import page


class VirtualWalletAction(enum.StrEnum):
    '''The type of virtual wallet action.'''
    RESPOND = 'respond'
    DECLINE = 'decline'
    WAIT = 'wait'
    CLEAR = 'clear'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> VirtualWalletAction:
        return cls(json)


def set_virtual_wallet_behavior(
        action: VirtualWalletAction,
        protocol: str | None = None,
        response: T_JSON_DICT | None = None,
        frame_id: page.FrameId | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Sets the behavior of the virtual wallet for digital credential requests
    issued from this frame.

    :param action: The action of the virtual wallet.
    :param protocol: *(Optional)* The protocol identifier (e.g. "openid4vp"). Required when |action| is "respond", forbidden otherwise.
    :param response: *(Optional)* The response data object returned by the wallet. Required when |action| is "respond", forbidden otherwise.
    :param frame_id: *(Optional)* The frame to scope the virtual wallet behavior to.
    '''
    params: T_JSON_DICT = {}
    params['action'] = action.to_json()
    if protocol is not None:
        params['protocol'] = protocol
    if response is not None:
        params['response'] = response
    if frame_id is not None:
        params['frameId'] = frame_id.to_json()
    yield {'method': 'DigitalCredentials.setVirtualWalletBehavior', 'params': params}
