# DO NOT EDIT — generated by purecdp._generator from DOMDebugger (devtools-protocol 3bd8f01934b5)
'''CDP domain: DOMDebugger.

DOM debugging allows setting breakpoints on particular DOM operations and events. JavaScript
execution will stop on these operations as if there was a regular breakpoint set.
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class

from . import dom, runtime


class DOMBreakpointType(enum.StrEnum):
    '''DOM breakpoint type.'''
    SUBTREE_MODIFIED = 'subtree-modified'
    ATTRIBUTE_MODIFIED = 'attribute-modified'
    NODE_REMOVED = 'node-removed'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> DOMBreakpointType:
        return cls(json)


class CSPViolationType(enum.StrEnum):
    '''CSP Violation type.

    **EXPERIMENTAL**
    '''
    TRUSTEDTYPE_SINK_VIOLATION = 'trustedtype-sink-violation'
    TRUSTEDTYPE_POLICY_VIOLATION = 'trustedtype-policy-violation'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> CSPViolationType:
        return cls(json)


@dataclass(slots=True)
class EventListener:
    '''Object event listener.'''
    #: `EventListener`'s type.
    type: str
    #: `EventListener`'s useCapture.
    use_capture: bool
    #: `EventListener`'s passive flag.
    passive: bool
    #: `EventListener`'s once flag.
    once: bool
    #: Script id of the handler code.
    script_id: runtime.ScriptId
    #: Line number in the script (0-based).
    line_number: int
    #: Column number in the script (0-based).
    column_number: int
    #: *(Optional)* Event handler function value.
    handler: runtime.RemoteObject | None = None
    #: *(Optional)* Event original handler function value.
    original_handler: runtime.RemoteObject | None = None
    #: *(Optional)* Node the listener is added to (if any).
    backend_node_id: dom.BackendNodeId | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['type'] = self.type
        json['useCapture'] = self.use_capture
        json['passive'] = self.passive
        json['once'] = self.once
        json['scriptId'] = self.script_id.to_json()
        json['lineNumber'] = self.line_number
        json['columnNumber'] = self.column_number
        if self.handler is not None:
            json['handler'] = self.handler.to_json()
        if self.original_handler is not None:
            json['originalHandler'] = self.original_handler.to_json()
        if self.backend_node_id is not None:
            json['backendNodeId'] = self.backend_node_id.to_json()
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> EventListener:
        return cls(
            type=json['type'],
            use_capture=json['useCapture'],
            passive=json['passive'],
            once=json['once'],
            script_id=runtime.ScriptId.from_json(json['scriptId']),
            line_number=json['lineNumber'],
            column_number=json['columnNumber'],
            handler=runtime.RemoteObject.from_json(json['handler']) if json.get('handler') is not None else None,
            original_handler=runtime.RemoteObject.from_json(json['originalHandler']) if json.get('originalHandler') is not None else None,
            backend_node_id=dom.BackendNodeId.from_json(json['backendNodeId']) if json.get('backendNodeId') is not None else None,
        )


def get_event_listeners(
        object_id: runtime.RemoteObjectId,
        depth: int | None = None,
        pierce: bool | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[EventListener]]:
    '''Returns event listeners of the given object.

    :param object_id: Identifier of the object to return listeners for.
    :param depth: *(Optional)* The maximum depth at which Node children should be retrieved, defaults to 1. Use -1 for the entire subtree or provide an integer larger than 0.
    :param pierce: *(Optional)* Whether or not iframes and shadow roots should be traversed when returning the subtree (default is false). Reports listeners for all contexts if pierce is enabled.
    :returns: Array of relevant listeners.
    '''
    params: T_JSON_DICT = {}
    params['objectId'] = object_id.to_json()
    if depth is not None:
        params['depth'] = depth
    if pierce is not None:
        params['pierce'] = pierce
    json = yield {'method': 'DOMDebugger.getEventListeners', 'params': params}
    return [EventListener.from_json(i) for i in json['listeners']]


def remove_dom_breakpoint(
        node_id: dom.NodeId,
        type: DOMBreakpointType,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Removes DOM breakpoint that was set using `setDOMBreakpoint`.

    :param node_id: Identifier of the node to remove breakpoint from.
    :param type: Type of the breakpoint to remove.
    '''
    params: T_JSON_DICT = {}
    params['nodeId'] = node_id.to_json()
    params['type'] = type.to_json()
    yield {'method': 'DOMDebugger.removeDOMBreakpoint', 'params': params}


def remove_event_listener_breakpoint(
        event_name: str,
        target_name: str | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Removes breakpoint on particular DOM event.

    :param event_name: Event name.
    :param target_name: *(Optional)* EventTarget interface name. *(EXPERIMENTAL)*
    '''
    params: T_JSON_DICT = {}
    params['eventName'] = event_name
    if target_name is not None:
        params['targetName'] = target_name
    yield {'method': 'DOMDebugger.removeEventListenerBreakpoint', 'params': params}


def remove_instrumentation_breakpoint(
        event_name: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Removes breakpoint on particular native event.

    **EXPERIMENTAL** **DEPRECATED**

    :param event_name: Instrumentation name to stop on.
    '''
    params: T_JSON_DICT = {}
    params['eventName'] = event_name
    yield {'method': 'DOMDebugger.removeInstrumentationBreakpoint', 'params': params}


def remove_xhr_breakpoint(url: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Removes breakpoint from XMLHttpRequest.

    :param url: Resource URL substring.
    '''
    params: T_JSON_DICT = {}
    params['url'] = url
    yield {'method': 'DOMDebugger.removeXHRBreakpoint', 'params': params}


def set_break_on_csp_violation(
        violation_types: list[CSPViolationType],
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Sets breakpoint on particular CSP violations.

    **EXPERIMENTAL**

    :param violation_types: CSP Violations to stop upon.
    '''
    params: T_JSON_DICT = {}
    params['violationTypes'] = [i.to_json() for i in violation_types]
    yield {'method': 'DOMDebugger.setBreakOnCSPViolation', 'params': params}


def set_dom_breakpoint(
        node_id: dom.NodeId,
        type: DOMBreakpointType,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Sets breakpoint on particular operation with DOM.

    :param node_id: Identifier of the node to set breakpoint on.
    :param type: Type of the operation to stop upon.
    '''
    params: T_JSON_DICT = {}
    params['nodeId'] = node_id.to_json()
    params['type'] = type.to_json()
    yield {'method': 'DOMDebugger.setDOMBreakpoint', 'params': params}


def set_event_listener_breakpoint(
        event_name: str,
        target_name: str | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Sets breakpoint on particular DOM event.

    :param event_name: DOM Event name to stop on (any DOM event will do).
    :param target_name: *(Optional)* EventTarget interface name to stop on. If equal to `"*"` or not provided, will stop on any EventTarget. *(EXPERIMENTAL)*
    '''
    params: T_JSON_DICT = {}
    params['eventName'] = event_name
    if target_name is not None:
        params['targetName'] = target_name
    yield {'method': 'DOMDebugger.setEventListenerBreakpoint', 'params': params}


def set_instrumentation_breakpoint(
        event_name: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Sets breakpoint on particular native event.

    **EXPERIMENTAL** **DEPRECATED**

    :param event_name: Instrumentation name to stop on.
    '''
    params: T_JSON_DICT = {}
    params['eventName'] = event_name
    yield {'method': 'DOMDebugger.setInstrumentationBreakpoint', 'params': params}


def set_xhr_breakpoint(url: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Sets breakpoint on XMLHttpRequest.

    :param url: Resource URL substring. All XHRs having this substring in the URL will get stopped upon.
    '''
    params: T_JSON_DICT = {}
    params['url'] = url
    yield {'method': 'DOMDebugger.setXHRBreakpoint', 'params': params}
