# DO NOT EDIT — generated by purecdp._generator from Extensions (devtools-protocol 3bd8f01934b5)
'''CDP domain: Extensions.

Defines commands and events for browser extensions.

**EXPERIMENTAL**
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class


class StorageArea(enum.StrEnum):
    '''Storage areas.'''
    SESSION = 'session'
    LOCAL = 'local'
    SYNC = 'sync'
    MANAGED = 'managed'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> StorageArea:
        return cls(json)


@dataclass(slots=True)
class ExtensionInfo:
    '''Detailed information about an extension.'''
    #: Extension id.
    id: str
    #: Extension name.
    name: str
    #: Extension version.
    version: str
    #: The path from which the extension was loaded.
    path: str
    #: Extension enabled status.
    enabled: bool

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['id'] = self.id
        json['name'] = self.name
        json['version'] = self.version
        json['path'] = self.path
        json['enabled'] = self.enabled
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ExtensionInfo:
        return cls(
            id=json['id'],
            name=json['name'],
            version=json['version'],
            path=json['path'],
            enabled=json['enabled'],
        )


def trigger_action(id: str, target_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Runs an extension default action.

    :param id: Extension id.
    :param target_id: A tab target ID to trigger the default extension action on.
    '''
    params: T_JSON_DICT = {}
    params['id'] = id
    params['targetId'] = target_id
    yield {'method': 'Extensions.triggerAction', 'params': params}


def load_unpacked(
        path: str,
        enable_in_incognito: bool | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, str]:
    '''Installs an unpacked extension from the filesystem similar to
    --load-extension CLI flags. Returns extension ID once the extension
    has been installed.

    :param path: Absolute file path.
    :param enable_in_incognito: *(Optional)* Enable the extension in incognito
    :returns: Extension id.
    '''
    params: T_JSON_DICT = {}
    params['path'] = path
    if enable_in_incognito is not None:
        params['enableInIncognito'] = enable_in_incognito
    json = yield {'method': 'Extensions.loadUnpacked', 'params': params}
    return json['id']


def get_extensions() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[ExtensionInfo]]:
    '''Gets a list of all unpacked extensions.

    :returns:
    '''
    json = yield {'method': 'Extensions.getExtensions'}
    return [ExtensionInfo.from_json(i) for i in json['extensions']]


def uninstall(id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Uninstalls an unpacked extension (others not supported) from the profile.

    :param id: Extension id.
    '''
    params: T_JSON_DICT = {}
    params['id'] = id
    yield {'method': 'Extensions.uninstall', 'params': params}


def get_storage_items(
        id: str,
        storage_area: StorageArea,
        keys: list[str] | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, T_JSON_DICT]:
    '''Gets data from extension storage in the given `storageArea`. If `keys` is
    specified, these are used to filter the result.

    :param id: ID of extension.
    :param storage_area: StorageArea to retrieve data from.
    :param keys: *(Optional)* Keys to retrieve.
    :returns:
    '''
    params: T_JSON_DICT = {}
    params['id'] = id
    params['storageArea'] = storage_area.to_json()
    if keys is not None:
        params['keys'] = list(keys)
    json = yield {'method': 'Extensions.getStorageItems', 'params': params}
    return json['data']


def remove_storage_items(
        id: str,
        storage_area: StorageArea,
        keys: list[str],
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Removes `keys` from extension storage in the given `storageArea`.

    :param id: ID of extension.
    :param storage_area: StorageArea to remove data from.
    :param keys: Keys to remove.
    '''
    params: T_JSON_DICT = {}
    params['id'] = id
    params['storageArea'] = storage_area.to_json()
    params['keys'] = list(keys)
    yield {'method': 'Extensions.removeStorageItems', 'params': params}


def clear_storage_items(
        id: str,
        storage_area: StorageArea,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Clears extension storage in the given `storageArea`.

    :param id: ID of extension.
    :param storage_area: StorageArea to remove data from.
    '''
    params: T_JSON_DICT = {}
    params['id'] = id
    params['storageArea'] = storage_area.to_json()
    yield {'method': 'Extensions.clearStorageItems', 'params': params}


def set_storage_items(
        id: str,
        storage_area: StorageArea,
        values: T_JSON_DICT,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Sets `values` in extension storage in the given `storageArea`. The provided `values`
    will be merged with existing values in the storage area.

    :param id: ID of extension.
    :param storage_area: StorageArea to set data in.
    :param values: Values to set.
    '''
    params: T_JSON_DICT = {}
    params['id'] = id
    params['storageArea'] = storage_area.to_json()
    params['values'] = values
    yield {'method': 'Extensions.setStorageItems', 'params': params}
