# DO NOT EDIT — generated by purecdp._generator from FileSystem (devtools-protocol 3bd8f01934b5)
'''CDP domain: FileSystem.

**EXPERIMENTAL**
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class

from . import network, storage


@dataclass(slots=True)
class File:
    name: str
    #: Timestamp
    last_modified: network.TimeSinceEpoch
    #: Size in bytes
    size: float
    type: str

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['name'] = self.name
        json['lastModified'] = self.last_modified.to_json()
        json['size'] = self.size
        json['type'] = self.type
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> File:
        return cls(
            name=json['name'],
            last_modified=network.TimeSinceEpoch.from_json(json['lastModified']),
            size=float(json['size']),
            type=json['type'],
        )


@dataclass(slots=True)
class Directory:
    name: str
    nested_directories: list[str]
    #: Files that are directly nested under this directory.
    nested_files: list[File]

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['name'] = self.name
        json['nestedDirectories'] = list(self.nested_directories)
        json['nestedFiles'] = [i.to_json() for i in self.nested_files]
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Directory:
        return cls(
            name=json['name'],
            nested_directories=list(json['nestedDirectories']),
            nested_files=[File.from_json(i) for i in json['nestedFiles']],
        )


@dataclass(slots=True)
class BucketFileSystemLocator:
    #: Storage key
    storage_key: storage.SerializedStorageKey
    #: Path to the directory using each path component as an array item.
    path_components: list[str]
    #: *(Optional)* Bucket name. Not passing a `bucketName` will retrieve the default Bucket. (https://developer.mozilla.org/en-US/docs/Web/API/Storage_API#storage_buckets)
    bucket_name: str | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['storageKey'] = self.storage_key.to_json()
        json['pathComponents'] = list(self.path_components)
        if self.bucket_name is not None:
            json['bucketName'] = self.bucket_name
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> BucketFileSystemLocator:
        return cls(
            storage_key=storage.SerializedStorageKey.from_json(json['storageKey']),
            path_components=list(json['pathComponents']),
            bucket_name=json['bucketName'] if json.get('bucketName') is not None else None,
        )


def get_directory(
        bucket_file_system_locator: BucketFileSystemLocator,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, Directory]:
    ''':param bucket_file_system_locator: 
    :returns: Returns the directory object at the path.
    '''
    params: T_JSON_DICT = {}
    params['bucketFileSystemLocator'] = bucket_file_system_locator.to_json()
    json = yield {'method': 'FileSystem.getDirectory', 'params': params}
    return Directory.from_json(json['directory'])
