# DO NOT EDIT — generated by purecdp._generator from IndexedDB (devtools-protocol 3bd8f01934b5)
'''CDP domain: IndexedDB.

**EXPERIMENTAL**
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class

from . import runtime, storage


@dataclass(slots=True)
class DatabaseWithObjectStores:
    '''Database with an array of object stores.'''
    #: Database name.
    name: str
    #: Database version (type is not 'integer', as the standard requires the version number to be 'unsigned long long')
    version: float
    #: Object stores in this database.
    object_stores: list[ObjectStore]

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['name'] = self.name
        json['version'] = self.version
        json['objectStores'] = [i.to_json() for i in self.object_stores]
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DatabaseWithObjectStores:
        return cls(
            name=json['name'],
            version=float(json['version']),
            object_stores=[ObjectStore.from_json(i) for i in json['objectStores']],
        )


@dataclass(slots=True)
class ObjectStore:
    '''Object store.'''
    #: Object store name.
    name: str
    #: Object store key path.
    key_path: KeyPath
    #: If true, object store has auto increment flag set.
    auto_increment: bool
    #: Indexes in this object store.
    indexes: list[ObjectStoreIndex]

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['name'] = self.name
        json['keyPath'] = self.key_path.to_json()
        json['autoIncrement'] = self.auto_increment
        json['indexes'] = [i.to_json() for i in self.indexes]
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ObjectStore:
        return cls(
            name=json['name'],
            key_path=KeyPath.from_json(json['keyPath']),
            auto_increment=json['autoIncrement'],
            indexes=[ObjectStoreIndex.from_json(i) for i in json['indexes']],
        )


@dataclass(slots=True)
class ObjectStoreIndex:
    '''Object store index.'''
    #: Index name.
    name: str
    #: Index key path.
    key_path: KeyPath
    #: If true, index is unique.
    unique: bool
    #: If true, index allows multiple entries for a key.
    multi_entry: bool

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['name'] = self.name
        json['keyPath'] = self.key_path.to_json()
        json['unique'] = self.unique
        json['multiEntry'] = self.multi_entry
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ObjectStoreIndex:
        return cls(
            name=json['name'],
            key_path=KeyPath.from_json(json['keyPath']),
            unique=json['unique'],
            multi_entry=json['multiEntry'],
        )


@dataclass(slots=True)
class Key:
    '''Key.'''
    #: Key type. Allowed values: number, string, date, array
    type: str
    #: *(Optional)* Number value.
    number: float | None = None
    #: *(Optional)* String value.
    string: str | None = None
    #: *(Optional)* Date value.
    date: float | None = None
    #: *(Optional)* Array value.
    array: list[Key] | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['type'] = self.type
        if self.number is not None:
            json['number'] = self.number
        if self.string is not None:
            json['string'] = self.string
        if self.date is not None:
            json['date'] = self.date
        if self.array is not None:
            json['array'] = [i.to_json() for i in self.array]
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Key:
        return cls(
            type=json['type'],
            number=float(json['number']) if json.get('number') is not None else None,
            string=json['string'] if json.get('string') is not None else None,
            date=float(json['date']) if json.get('date') is not None else None,
            array=[Key.from_json(i) for i in json['array']] if json.get('array') is not None else None,
        )


@dataclass(slots=True)
class KeyRange:
    '''Key range.'''
    #: If true lower bound is open.
    lower_open: bool
    #: If true upper bound is open.
    upper_open: bool
    #: *(Optional)* Lower bound.
    lower: Key | None = None
    #: *(Optional)* Upper bound.
    upper: Key | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['lowerOpen'] = self.lower_open
        json['upperOpen'] = self.upper_open
        if self.lower is not None:
            json['lower'] = self.lower.to_json()
        if self.upper is not None:
            json['upper'] = self.upper.to_json()
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> KeyRange:
        return cls(
            lower_open=json['lowerOpen'],
            upper_open=json['upperOpen'],
            lower=Key.from_json(json['lower']) if json.get('lower') is not None else None,
            upper=Key.from_json(json['upper']) if json.get('upper') is not None else None,
        )


@dataclass(slots=True)
class DataEntry:
    '''Data entry.'''
    #: Key object.
    key: runtime.RemoteObject
    #: Primary key object.
    primary_key: runtime.RemoteObject
    #: Value object.
    value: runtime.RemoteObject

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['key'] = self.key.to_json()
        json['primaryKey'] = self.primary_key.to_json()
        json['value'] = self.value.to_json()
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DataEntry:
        return cls(
            key=runtime.RemoteObject.from_json(json['key']),
            primary_key=runtime.RemoteObject.from_json(json['primaryKey']),
            value=runtime.RemoteObject.from_json(json['value']),
        )


@dataclass(slots=True)
class KeyPath:
    '''Key path.'''
    #: Key path type. Allowed values: null, string, array
    type: str
    #: *(Optional)* String value.
    string: str | None = None
    #: *(Optional)* Array value.
    array: list[str] | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['type'] = self.type
        if self.string is not None:
            json['string'] = self.string
        if self.array is not None:
            json['array'] = list(self.array)
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> KeyPath:
        return cls(
            type=json['type'],
            string=json['string'] if json.get('string') is not None else None,
            array=list(json['array']) if json.get('array') is not None else None,
        )


def clear_object_store(
        database_name: str,
        object_store_name: str,
        security_origin: str | None = None,
        storage_key: str | None = None,
        storage_bucket: storage.StorageBucket | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Clears all entries from an object store.

    :param database_name: Database name.
    :param object_store_name: Object store name.
    :param security_origin: *(Optional)* At least and at most one of securityOrigin, storageKey, or storageBucket must be specified. Security origin.
    :param storage_key: *(Optional)* Storage key.
    :param storage_bucket: *(Optional)* Storage bucket. If not specified, it uses the default bucket.
    '''
    params: T_JSON_DICT = {}
    params['databaseName'] = database_name
    params['objectStoreName'] = object_store_name
    if security_origin is not None:
        params['securityOrigin'] = security_origin
    if storage_key is not None:
        params['storageKey'] = storage_key
    if storage_bucket is not None:
        params['storageBucket'] = storage_bucket.to_json()
    yield {'method': 'IndexedDB.clearObjectStore', 'params': params}


def delete_database(
        database_name: str,
        security_origin: str | None = None,
        storage_key: str | None = None,
        storage_bucket: storage.StorageBucket | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Deletes a database.

    :param database_name: Database name.
    :param security_origin: *(Optional)* At least and at most one of securityOrigin, storageKey, or storageBucket must be specified. Security origin.
    :param storage_key: *(Optional)* Storage key.
    :param storage_bucket: *(Optional)* Storage bucket. If not specified, it uses the default bucket.
    '''
    params: T_JSON_DICT = {}
    params['databaseName'] = database_name
    if security_origin is not None:
        params['securityOrigin'] = security_origin
    if storage_key is not None:
        params['storageKey'] = storage_key
    if storage_bucket is not None:
        params['storageBucket'] = storage_bucket.to_json()
    yield {'method': 'IndexedDB.deleteDatabase', 'params': params}


def delete_object_store_entries(
        database_name: str,
        object_store_name: str,
        key_range: KeyRange,
        security_origin: str | None = None,
        storage_key: str | None = None,
        storage_bucket: storage.StorageBucket | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Delete a range of entries from an object store

    :param database_name:
    :param object_store_name:
    :param key_range: Range of entry keys to delete
    :param security_origin: *(Optional)* At least and at most one of securityOrigin, storageKey, or storageBucket must be specified. Security origin.
    :param storage_key: *(Optional)* Storage key.
    :param storage_bucket: *(Optional)* Storage bucket. If not specified, it uses the default bucket.
    '''
    params: T_JSON_DICT = {}
    params['databaseName'] = database_name
    params['objectStoreName'] = object_store_name
    params['keyRange'] = key_range.to_json()
    if security_origin is not None:
        params['securityOrigin'] = security_origin
    if storage_key is not None:
        params['storageKey'] = storage_key
    if storage_bucket is not None:
        params['storageBucket'] = storage_bucket.to_json()
    yield {'method': 'IndexedDB.deleteObjectStoreEntries', 'params': params}


def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Disables events from backend.'''
    yield {'method': 'IndexedDB.disable'}


def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Enables events from backend.'''
    yield {'method': 'IndexedDB.enable'}


def request_data(
        database_name: str,
        object_store_name: str,
        skip_count: int,
        page_size: int,
        security_origin: str | None = None,
        storage_key: str | None = None,
        storage_bucket: storage.StorageBucket | None = None,
        index_name: str | None = None,
        key_range: KeyRange | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, tuple[list[DataEntry], bool]]:
    '''Requests data from object store or index.

    :param database_name: Database name.
    :param object_store_name: Object store name.
    :param skip_count: Number of records to skip.
    :param page_size: Number of records to fetch.
    :param security_origin: *(Optional)* At least and at most one of securityOrigin, storageKey, or storageBucket must be specified. Security origin.
    :param storage_key: *(Optional)* Storage key.
    :param storage_bucket: *(Optional)* Storage bucket. If not specified, it uses the default bucket.
    :param index_name: *(Optional)* Index name. If not specified, it performs an object store data request.
    :param key_range: *(Optional)* Key range.
    :returns: A tuple with the following items:
        0. **objectStoreDataEntries** — Array of object store data entries.
        1. **hasMore** — If true, there are more entries to fetch in the given range.
    '''
    params: T_JSON_DICT = {}
    params['databaseName'] = database_name
    params['objectStoreName'] = object_store_name
    params['skipCount'] = skip_count
    params['pageSize'] = page_size
    if security_origin is not None:
        params['securityOrigin'] = security_origin
    if storage_key is not None:
        params['storageKey'] = storage_key
    if storage_bucket is not None:
        params['storageBucket'] = storage_bucket.to_json()
    if index_name is not None:
        params['indexName'] = index_name
    if key_range is not None:
        params['keyRange'] = key_range.to_json()
    json = yield {'method': 'IndexedDB.requestData', 'params': params}
    return (
        [DataEntry.from_json(i) for i in json['objectStoreDataEntries']],
        json['hasMore'],
    )


def get_metadata(
        database_name: str,
        object_store_name: str,
        security_origin: str | None = None,
        storage_key: str | None = None,
        storage_bucket: storage.StorageBucket | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, tuple[float, float]]:
    '''Gets metadata of an object store.

    :param database_name: Database name.
    :param object_store_name: Object store name.
    :param security_origin: *(Optional)* At least and at most one of securityOrigin, storageKey, or storageBucket must be specified. Security origin.
    :param storage_key: *(Optional)* Storage key.
    :param storage_bucket: *(Optional)* Storage bucket. If not specified, it uses the default bucket.
    :returns: A tuple with the following items:
        0. **entriesCount** — the entries count
        1. **keyGeneratorValue** — the current value of key generator, to become the next inserted key into the object store. Valid if objectStore.autoIncrement is true.
    '''
    params: T_JSON_DICT = {}
    params['databaseName'] = database_name
    params['objectStoreName'] = object_store_name
    if security_origin is not None:
        params['securityOrigin'] = security_origin
    if storage_key is not None:
        params['storageKey'] = storage_key
    if storage_bucket is not None:
        params['storageBucket'] = storage_bucket.to_json()
    json = yield {'method': 'IndexedDB.getMetadata', 'params': params}
    return (
        float(json['entriesCount']),
        float(json['keyGeneratorValue']),
    )


def request_database(
        database_name: str,
        security_origin: str | None = None,
        storage_key: str | None = None,
        storage_bucket: storage.StorageBucket | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, DatabaseWithObjectStores]:
    '''Requests database with given name in given frame.

    :param database_name: Database name.
    :param security_origin: *(Optional)* At least and at most one of securityOrigin, storageKey, or storageBucket must be specified. Security origin.
    :param storage_key: *(Optional)* Storage key.
    :param storage_bucket: *(Optional)* Storage bucket. If not specified, it uses the default bucket.
    :returns: Database with an array of object stores.
    '''
    params: T_JSON_DICT = {}
    params['databaseName'] = database_name
    if security_origin is not None:
        params['securityOrigin'] = security_origin
    if storage_key is not None:
        params['storageKey'] = storage_key
    if storage_bucket is not None:
        params['storageBucket'] = storage_bucket.to_json()
    json = yield {'method': 'IndexedDB.requestDatabase', 'params': params}
    return DatabaseWithObjectStores.from_json(json['databaseWithObjectStores'])


def request_database_names(
        security_origin: str | None = None,
        storage_key: str | None = None,
        storage_bucket: storage.StorageBucket | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[str]]:
    '''Requests database names for given security origin.

    :param security_origin: *(Optional)* At least and at most one of securityOrigin, storageKey, or storageBucket must be specified. Security origin.
    :param storage_key: *(Optional)* Storage key.
    :param storage_bucket: *(Optional)* Storage bucket. If not specified, it uses the default bucket.
    :returns: Database names for origin.
    '''
    params: T_JSON_DICT = {}
    if security_origin is not None:
        params['securityOrigin'] = security_origin
    if storage_key is not None:
        params['storageKey'] = storage_key
    if storage_bucket is not None:
        params['storageBucket'] = storage_bucket.to_json()
    json = yield {'method': 'IndexedDB.requestDatabaseNames', 'params': params}
    return list(json['databaseNames'])
