# DO NOT EDIT — generated by purecdp._generator from LayerTree (devtools-protocol 3bd8f01934b5)
'''CDP domain: LayerTree.

**EXPERIMENTAL**
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class

from . import dom


class LayerId(str):
    '''Unique Layer identifier.'''
    def to_json(self) -> str:
        return str(self)

    @classmethod
    def from_json(cls, json: str) -> LayerId:
        return cls(json)

    def __repr__(self) -> str:
        return f'LayerId({str.__repr__(self)})'


class SnapshotId(str):
    '''Unique snapshot identifier.'''
    def to_json(self) -> str:
        return str(self)

    @classmethod
    def from_json(cls, json: str) -> SnapshotId:
        return cls(json)

    def __repr__(self) -> str:
        return f'SnapshotId({str.__repr__(self)})'


@dataclass(slots=True)
class ScrollRect:
    '''Rectangle where scrolling happens on the main thread.'''
    #: Rectangle itself.
    rect: dom.Rect
    #: Reason for rectangle to force scrolling on the main thread Allowed values: RepaintsOnScroll, TouchEventHandler, WheelEventHandler
    type: str

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['rect'] = self.rect.to_json()
        json['type'] = self.type
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ScrollRect:
        return cls(
            rect=dom.Rect.from_json(json['rect']),
            type=json['type'],
        )


@dataclass(slots=True)
class StickyPositionConstraint:
    '''Sticky position constraints.'''
    #: Layout rectangle of the sticky element before being shifted
    sticky_box_rect: dom.Rect
    #: Layout rectangle of the containing block of the sticky element
    containing_block_rect: dom.Rect
    #: *(Optional)* The nearest sticky layer that shifts the sticky box
    nearest_layer_shifting_sticky_box: LayerId | None = None
    #: *(Optional)* The nearest sticky layer that shifts the containing block
    nearest_layer_shifting_containing_block: LayerId | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['stickyBoxRect'] = self.sticky_box_rect.to_json()
        json['containingBlockRect'] = self.containing_block_rect.to_json()
        if self.nearest_layer_shifting_sticky_box is not None:
            json['nearestLayerShiftingStickyBox'] = self.nearest_layer_shifting_sticky_box.to_json()
        if self.nearest_layer_shifting_containing_block is not None:
            json['nearestLayerShiftingContainingBlock'] = self.nearest_layer_shifting_containing_block.to_json()
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> StickyPositionConstraint:
        return cls(
            sticky_box_rect=dom.Rect.from_json(json['stickyBoxRect']),
            containing_block_rect=dom.Rect.from_json(json['containingBlockRect']),
            nearest_layer_shifting_sticky_box=LayerId.from_json(json['nearestLayerShiftingStickyBox']) if json.get('nearestLayerShiftingStickyBox') is not None else None,
            nearest_layer_shifting_containing_block=LayerId.from_json(json['nearestLayerShiftingContainingBlock']) if json.get('nearestLayerShiftingContainingBlock') is not None else None,
        )


@dataclass(slots=True)
class PictureTile:
    '''Serialized fragment of layer picture along with its offset within the layer.'''
    #: Offset from owning layer left boundary
    x: float
    #: Offset from owning layer top boundary
    y: float
    #: Base64-encoded snapshot data. (Encoded as a base64 string when passed over JSON)
    picture: str

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['x'] = self.x
        json['y'] = self.y
        json['picture'] = self.picture
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PictureTile:
        return cls(
            x=float(json['x']),
            y=float(json['y']),
            picture=json['picture'],
        )


@dataclass(slots=True)
class Layer:
    '''Information about a compositing layer.'''
    #: The unique id for this layer.
    layer_id: LayerId
    #: Offset from parent layer, X coordinate.
    offset_x: float
    #: Offset from parent layer, Y coordinate.
    offset_y: float
    #: Layer width.
    width: float
    #: Layer height.
    height: float
    #: Indicates how many time this layer has painted.
    paint_count: int
    #: Indicates whether this layer hosts any content, rather than being used for transform/scrolling purposes only.
    draws_content: bool
    #: *(Optional)* The id of parent (not present for root).
    parent_layer_id: LayerId | None = None
    #: *(Optional)* The backend id for the node associated with this layer.
    backend_node_id: dom.BackendNodeId | None = None
    #: *(Optional)* Transformation matrix for layer, default is identity matrix
    transform: list[float] | None = None
    #: *(Optional)* Transform anchor point X, absent if no transform specified
    anchor_x: float | None = None
    #: *(Optional)* Transform anchor point Y, absent if no transform specified
    anchor_y: float | None = None
    #: *(Optional)* Transform anchor point Z, absent if no transform specified
    anchor_z: float | None = None
    #: *(Optional)* Set if layer is not visible.
    invisible: bool | None = None
    #: *(Optional)* Rectangles scrolling on main thread only.
    scroll_rects: list[ScrollRect] | None = None
    #: *(Optional)* Sticky position constraint information
    sticky_position_constraint: StickyPositionConstraint | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['layerId'] = self.layer_id.to_json()
        json['offsetX'] = self.offset_x
        json['offsetY'] = self.offset_y
        json['width'] = self.width
        json['height'] = self.height
        json['paintCount'] = self.paint_count
        json['drawsContent'] = self.draws_content
        if self.parent_layer_id is not None:
            json['parentLayerId'] = self.parent_layer_id.to_json()
        if self.backend_node_id is not None:
            json['backendNodeId'] = self.backend_node_id.to_json()
        if self.transform is not None:
            json['transform'] = list(self.transform)
        if self.anchor_x is not None:
            json['anchorX'] = self.anchor_x
        if self.anchor_y is not None:
            json['anchorY'] = self.anchor_y
        if self.anchor_z is not None:
            json['anchorZ'] = self.anchor_z
        if self.invisible is not None:
            json['invisible'] = self.invisible
        if self.scroll_rects is not None:
            json['scrollRects'] = [i.to_json() for i in self.scroll_rects]
        if self.sticky_position_constraint is not None:
            json['stickyPositionConstraint'] = self.sticky_position_constraint.to_json()
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Layer:
        return cls(
            layer_id=LayerId.from_json(json['layerId']),
            offset_x=float(json['offsetX']),
            offset_y=float(json['offsetY']),
            width=float(json['width']),
            height=float(json['height']),
            paint_count=json['paintCount'],
            draws_content=json['drawsContent'],
            parent_layer_id=LayerId.from_json(json['parentLayerId']) if json.get('parentLayerId') is not None else None,
            backend_node_id=dom.BackendNodeId.from_json(json['backendNodeId']) if json.get('backendNodeId') is not None else None,
            transform=[float(i) for i in json['transform']] if json.get('transform') is not None else None,
            anchor_x=float(json['anchorX']) if json.get('anchorX') is not None else None,
            anchor_y=float(json['anchorY']) if json.get('anchorY') is not None else None,
            anchor_z=float(json['anchorZ']) if json.get('anchorZ') is not None else None,
            invisible=json['invisible'] if json.get('invisible') is not None else None,
            scroll_rects=[ScrollRect.from_json(i) for i in json['scrollRects']] if json.get('scrollRects') is not None else None,
            sticky_position_constraint=StickyPositionConstraint.from_json(json['stickyPositionConstraint']) if json.get('stickyPositionConstraint') is not None else None,
        )


class PaintProfile(list):
    '''Array of timings, one per paint step.'''
    def to_json(self) -> list:
        return list(self)

    @classmethod
    def from_json(cls, json: list) -> PaintProfile:
        return cls([float(i) for i in json])

    def __repr__(self) -> str:
        return f'PaintProfile({list.__repr__(self)})'


def compositing_reasons(
        layer_id: LayerId,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, tuple[list[str], list[str]]]:
    '''Provides the reasons why the given layer was composited.

    :param layer_id: The id of the layer for which we want to get the reasons it was composited.
    :returns: A tuple with the following items:
        0. **compositingReasons** — A list of strings specifying reasons for the given layer to become composited.
        1. **compositingReasonIds** — A list of strings specifying reason IDs for the given layer to become composited.
    '''
    params: T_JSON_DICT = {}
    params['layerId'] = layer_id.to_json()
    json = yield {'method': 'LayerTree.compositingReasons', 'params': params}
    return (
        list(json['compositingReasons']),
        list(json['compositingReasonIds']),
    )


def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Disables compositing tree inspection.'''
    yield {'method': 'LayerTree.disable'}


def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Enables compositing tree inspection.'''
    yield {'method': 'LayerTree.enable'}


def load_snapshot(
        tiles: list[PictureTile],
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SnapshotId]:
    '''Returns the snapshot identifier.

    :param tiles: An array of tiles composing the snapshot.
    :returns: The id of the snapshot.
    '''
    params: T_JSON_DICT = {}
    params['tiles'] = [i.to_json() for i in tiles]
    json = yield {'method': 'LayerTree.loadSnapshot', 'params': params}
    return SnapshotId.from_json(json['snapshotId'])


def make_snapshot(layer_id: LayerId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SnapshotId]:
    '''Returns the layer snapshot identifier.

    :param layer_id: The id of the layer.
    :returns: The id of the layer snapshot.
    '''
    params: T_JSON_DICT = {}
    params['layerId'] = layer_id.to_json()
    json = yield {'method': 'LayerTree.makeSnapshot', 'params': params}
    return SnapshotId.from_json(json['snapshotId'])


def profile_snapshot(
        snapshot_id: SnapshotId,
        min_repeat_count: int | None = None,
        min_duration: float | None = None,
        clip_rect: dom.Rect | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[PaintProfile]]:
    ''':param snapshot_id: The id of the layer snapshot.
    :param min_repeat_count: *(Optional)* The maximum number of times to replay the snapshot (1, if not specified).
    :param min_duration: *(Optional)* The minimum duration (in seconds) to replay the snapshot.
    :param clip_rect: *(Optional)* The clip rectangle to apply when replaying the snapshot.
    :returns: The array of paint profiles, one per run.
    '''
    params: T_JSON_DICT = {}
    params['snapshotId'] = snapshot_id.to_json()
    if min_repeat_count is not None:
        params['minRepeatCount'] = min_repeat_count
    if min_duration is not None:
        params['minDuration'] = min_duration
    if clip_rect is not None:
        params['clipRect'] = clip_rect.to_json()
    json = yield {'method': 'LayerTree.profileSnapshot', 'params': params}
    return [PaintProfile.from_json(i) for i in json['timings']]


def release_snapshot(snapshot_id: SnapshotId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Releases layer snapshot captured by the back-end.

    :param snapshot_id: The id of the layer snapshot.
    '''
    params: T_JSON_DICT = {}
    params['snapshotId'] = snapshot_id.to_json()
    yield {'method': 'LayerTree.releaseSnapshot', 'params': params}


def replay_snapshot(
        snapshot_id: SnapshotId,
        from_step: int | None = None,
        to_step: int | None = None,
        scale: float | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, str]:
    '''Replays the layer snapshot and returns the resulting bitmap.

    :param snapshot_id: The id of the layer snapshot.
    :param from_step: *(Optional)* The first step to replay from (replay from the very start if not specified).
    :param to_step: *(Optional)* The last step to replay to (replay till the end if not specified).
    :param scale: *(Optional)* The scale to apply while replaying (defaults to 1).
    :returns: A data: URL for resulting image.
    '''
    params: T_JSON_DICT = {}
    params['snapshotId'] = snapshot_id.to_json()
    if from_step is not None:
        params['fromStep'] = from_step
    if to_step is not None:
        params['toStep'] = to_step
    if scale is not None:
        params['scale'] = scale
    json = yield {'method': 'LayerTree.replaySnapshot', 'params': params}
    return json['dataURL']


def snapshot_command_log(
        snapshot_id: SnapshotId,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[T_JSON_DICT]]:
    '''Replays the layer snapshot and returns canvas log.

    :param snapshot_id: The id of the layer snapshot.
    :returns: The array of canvas function calls.
    '''
    params: T_JSON_DICT = {}
    params['snapshotId'] = snapshot_id.to_json()
    json = yield {'method': 'LayerTree.snapshotCommandLog', 'params': params}
    return list(json['commandLog'])


@event_class('LayerTree.layerPainted')
@dataclass(slots=True)
class LayerPainted:
    #: The id of the painted layer.
    layer_id: LayerId
    #: Clip rectangle.
    clip: dom.Rect

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LayerPainted:
        return cls(
            layer_id=LayerId.from_json(json['layerId']),
            clip=dom.Rect.from_json(json['clip']),
        )


@event_class('LayerTree.layerTreeDidChange')
@dataclass(slots=True)
class LayerTreeDidChange:
    #: *(Optional)* Layer tree, absent if not in the compositing mode.
    layers: list[Layer] | None = None

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LayerTreeDidChange:
        return cls(
            layers=[Layer.from_json(i) for i in json['layers']] if json.get('layers') is not None else None,
        )
