# DO NOT EDIT — generated by purecdp._generator from Memory (devtools-protocol 3bd8f01934b5)
'''CDP domain: Memory.

**EXPERIMENTAL**
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class


class PressureLevel(enum.StrEnum):
    '''Memory pressure level.'''
    MODERATE = 'moderate'
    CRITICAL = 'critical'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> PressureLevel:
        return cls(json)


@dataclass(slots=True)
class SamplingProfileNode:
    '''Heap profile sample.'''
    #: Size of the sampled allocation.
    size: float
    #: Total bytes attributed to this sample.
    total: float
    #: Execution stack at the point of allocation.
    stack: list[str]

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['size'] = self.size
        json['total'] = self.total
        json['stack'] = list(self.stack)
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SamplingProfileNode:
        return cls(
            size=float(json['size']),
            total=float(json['total']),
            stack=list(json['stack']),
        )


@dataclass(slots=True)
class SamplingProfile:
    '''Array of heap profile samples.'''
    samples: list[SamplingProfileNode]
    modules: list[Module]

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['samples'] = [i.to_json() for i in self.samples]
        json['modules'] = [i.to_json() for i in self.modules]
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SamplingProfile:
        return cls(
            samples=[SamplingProfileNode.from_json(i) for i in json['samples']],
            modules=[Module.from_json(i) for i in json['modules']],
        )


@dataclass(slots=True)
class Module:
    '''Executable module information'''
    #: Name of the module.
    name: str
    #: UUID of the module.
    uuid: str
    #: Base address where the module is loaded into memory. Encoded as a decimal or hexadecimal (0x prefixed) string.
    base_address: str
    #: Size of the module in bytes.
    size: float

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['name'] = self.name
        json['uuid'] = self.uuid
        json['baseAddress'] = self.base_address
        json['size'] = self.size
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Module:
        return cls(
            name=json['name'],
            uuid=json['uuid'],
            base_address=json['baseAddress'],
            size=float(json['size']),
        )


@dataclass(slots=True)
class DOMCounter:
    '''DOM object counter data.'''
    #: Object name. Note: object names should be presumed volatile and clients should not expect the returned names to be consistent across runs.
    name: str
    #: Object count.
    count: int

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['name'] = self.name
        json['count'] = self.count
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DOMCounter:
        return cls(
            name=json['name'],
            count=json['count'],
        )


def get_dom_counters() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, tuple[int, int, int]]:
    '''Retruns current DOM object counters.

    :returns: A tuple with the following items:
        0. **documents** —
        1. **nodes** —
        2. **jsEventListeners** —
    '''
    json = yield {'method': 'Memory.getDOMCounters'}
    return (
        json['documents'],
        json['nodes'],
        json['jsEventListeners'],
    )


def get_dom_counters_for_leak_detection() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[DOMCounter]]:
    '''Retruns DOM object counters after preparing renderer for leak detection.

    :returns: DOM object counters.
    '''
    json = yield {'method': 'Memory.getDOMCountersForLeakDetection'}
    return [DOMCounter.from_json(i) for i in json['counters']]


def prepare_for_leak_detection() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Prepares for leak detection by terminating workers, stopping spellcheckers,
    dropping non-essential internal caches, running garbage collections, etc.
    '''
    yield {'method': 'Memory.prepareForLeakDetection'}


def forcibly_purge_java_script_memory() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Simulate OomIntervention by purging V8 memory.'''
    yield {'method': 'Memory.forciblyPurgeJavaScriptMemory'}


def set_pressure_notifications_suppressed(
        suppressed: bool,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Enable/disable suppressing memory pressure notifications in all processes.

    :param suppressed: If true, memory pressure notifications will be suppressed.
    '''
    params: T_JSON_DICT = {}
    params['suppressed'] = suppressed
    yield {'method': 'Memory.setPressureNotificationsSuppressed', 'params': params}


def simulate_pressure_notification(
        level: PressureLevel,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Simulate a memory pressure notification in all processes.

    :param level: Memory pressure level of the notification.
    '''
    params: T_JSON_DICT = {}
    params['level'] = level.to_json()
    yield {'method': 'Memory.simulatePressureNotification', 'params': params}


def start_sampling(
        sampling_interval: int | None = None,
        suppress_randomness: bool | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Start collecting native memory profile.

    :param sampling_interval: *(Optional)* Average number of bytes between samples.
    :param suppress_randomness: *(Optional)* Do not randomize intervals between samples.
    '''
    params: T_JSON_DICT = {}
    if sampling_interval is not None:
        params['samplingInterval'] = sampling_interval
    if suppress_randomness is not None:
        params['suppressRandomness'] = suppress_randomness
    yield {'method': 'Memory.startSampling', 'params': params}


def stop_sampling() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Stop collecting native memory profile.'''
    yield {'method': 'Memory.stopSampling'}


def get_all_time_sampling_profile() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SamplingProfile]:
    '''Retrieve native memory allocations profile
    collected since renderer process startup.

    :returns:
    '''
    json = yield {'method': 'Memory.getAllTimeSamplingProfile'}
    return SamplingProfile.from_json(json['profile'])


def get_browser_sampling_profile() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SamplingProfile]:
    '''Retrieve native memory allocations profile
    collected since browser process startup.

    :returns:
    '''
    json = yield {'method': 'Memory.getBrowserSamplingProfile'}
    return SamplingProfile.from_json(json['profile'])


def get_sampling_profile() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SamplingProfile]:
    '''Retrieve native memory allocations profile collected since last
    `startSampling` call.

    :returns:
    '''
    json = yield {'method': 'Memory.getSamplingProfile'}
    return SamplingProfile.from_json(json['profile'])
