# DO NOT EDIT — generated by purecdp._generator from Performance (devtools-protocol 3bd8f01934b5)
'''CDP domain: Performance.'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class


@dataclass(slots=True)
class Metric:
    '''Run-time execution metric.'''
    #: Metric name.
    name: str
    #: Metric value.
    value: float

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['name'] = self.name
        json['value'] = self.value
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Metric:
        return cls(
            name=json['name'],
            value=float(json['value']),
        )


def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Disable collecting and reporting metrics.'''
    yield {'method': 'Performance.disable'}


def enable(time_domain: str | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Enable collecting and reporting metrics.

    :param time_domain: *(Optional)* Time domain to use for collecting and reporting duration metrics. Allowed values: timeTicks, threadTicks
    '''
    params: T_JSON_DICT = {}
    if time_domain is not None:
        params['timeDomain'] = time_domain
    yield {'method': 'Performance.enable', 'params': params}


def set_time_domain(time_domain: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Sets time domain to use for collecting and reporting duration metrics.
    Note that this must be called before enabling metrics collection. Calling
    this method while metrics collection is enabled returns an error.

    **EXPERIMENTAL** **DEPRECATED**

    :param time_domain: Time domain Allowed values: timeTicks, threadTicks
    '''
    params: T_JSON_DICT = {}
    params['timeDomain'] = time_domain
    yield {'method': 'Performance.setTimeDomain', 'params': params}


def get_metrics() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[Metric]]:
    '''Retrieve current values of run-time metrics.

    :returns: Current values for run-time metrics.
    '''
    json = yield {'method': 'Performance.getMetrics'}
    return [Metric.from_json(i) for i in json['metrics']]


@event_class('Performance.metrics')
@dataclass(slots=True)
class Metrics:
    '''Current values of the metrics.'''
    #: Current values of the metrics.
    metrics: list[Metric]
    #: Timestamp title.
    title: str

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Metrics:
        return cls(
            metrics=[Metric.from_json(i) for i in json['metrics']],
            title=json['title'],
        )
