# DO NOT EDIT — generated by purecdp._generator from Profiler (devtools-protocol 3bd8f01934b5)
'''CDP domain: Profiler.'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class

from . import debugger, runtime


@dataclass(slots=True)
class ProfileNode:
    '''Profile node. Holds callsite information, execution statistics and child nodes.'''
    #: Unique id of the node.
    id: int
    #: Function location.
    call_frame: runtime.CallFrame
    #: *(Optional)* Number of samples where this node was on top of the call stack.
    hit_count: int | None = None
    #: *(Optional)* Child node ids.
    children: list[int] | None = None
    #: *(Optional)* The reason of being not optimized. The function may be deoptimized or marked as don't optimize.
    deopt_reason: str | None = None
    #: *(Optional)* An array of source position ticks.
    position_ticks: list[PositionTickInfo] | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['id'] = self.id
        json['callFrame'] = self.call_frame.to_json()
        if self.hit_count is not None:
            json['hitCount'] = self.hit_count
        if self.children is not None:
            json['children'] = list(self.children)
        if self.deopt_reason is not None:
            json['deoptReason'] = self.deopt_reason
        if self.position_ticks is not None:
            json['positionTicks'] = [i.to_json() for i in self.position_ticks]
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ProfileNode:
        return cls(
            id=json['id'],
            call_frame=runtime.CallFrame.from_json(json['callFrame']),
            hit_count=json['hitCount'] if json.get('hitCount') is not None else None,
            children=list(json['children']) if json.get('children') is not None else None,
            deopt_reason=json['deoptReason'] if json.get('deoptReason') is not None else None,
            position_ticks=[PositionTickInfo.from_json(i) for i in json['positionTicks']] if json.get('positionTicks') is not None else None,
        )


@dataclass(slots=True)
class Profile:
    '''Profile.'''
    #: The list of profile nodes. First item is the root node.
    nodes: list[ProfileNode]
    #: Profiling start timestamp in microseconds.
    start_time: float
    #: Profiling end timestamp in microseconds.
    end_time: float
    #: *(Optional)* Ids of samples top nodes.
    samples: list[int] | None = None
    #: *(Optional)* Time intervals between adjacent samples in microseconds. The first delta is relative to the profile startTime.
    time_deltas: list[int] | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['nodes'] = [i.to_json() for i in self.nodes]
        json['startTime'] = self.start_time
        json['endTime'] = self.end_time
        if self.samples is not None:
            json['samples'] = list(self.samples)
        if self.time_deltas is not None:
            json['timeDeltas'] = list(self.time_deltas)
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Profile:
        return cls(
            nodes=[ProfileNode.from_json(i) for i in json['nodes']],
            start_time=float(json['startTime']),
            end_time=float(json['endTime']),
            samples=list(json['samples']) if json.get('samples') is not None else None,
            time_deltas=list(json['timeDeltas']) if json.get('timeDeltas') is not None else None,
        )


@dataclass(slots=True)
class PositionTickInfo:
    '''Specifies a number of samples attributed to a certain source position.'''
    #: Source line number (1-based).
    line: int
    #: Number of samples attributed to the source line.
    ticks: int

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['line'] = self.line
        json['ticks'] = self.ticks
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PositionTickInfo:
        return cls(
            line=json['line'],
            ticks=json['ticks'],
        )


@dataclass(slots=True)
class CoverageRange:
    '''Coverage data for a source range.'''
    #: JavaScript script source offset for the range start.
    start_offset: int
    #: JavaScript script source offset for the range end.
    end_offset: int
    #: Collected execution count of the source range.
    count: int

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['startOffset'] = self.start_offset
        json['endOffset'] = self.end_offset
        json['count'] = self.count
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CoverageRange:
        return cls(
            start_offset=json['startOffset'],
            end_offset=json['endOffset'],
            count=json['count'],
        )


@dataclass(slots=True)
class FunctionCoverage:
    '''Coverage data for a JavaScript function.'''
    #: JavaScript function name.
    function_name: str
    #: Source ranges inside the function with coverage data.
    ranges: list[CoverageRange]
    #: Whether coverage data for this function has block granularity.
    is_block_coverage: bool

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['functionName'] = self.function_name
        json['ranges'] = [i.to_json() for i in self.ranges]
        json['isBlockCoverage'] = self.is_block_coverage
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> FunctionCoverage:
        return cls(
            function_name=json['functionName'],
            ranges=[CoverageRange.from_json(i) for i in json['ranges']],
            is_block_coverage=json['isBlockCoverage'],
        )


@dataclass(slots=True)
class ScriptCoverage:
    '''Coverage data for a JavaScript script.'''
    #: JavaScript script id.
    script_id: runtime.ScriptId
    #: JavaScript script name or url.
    url: str
    #: Functions contained in the script that has coverage data.
    functions: list[FunctionCoverage]

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['scriptId'] = self.script_id.to_json()
        json['url'] = self.url
        json['functions'] = [i.to_json() for i in self.functions]
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ScriptCoverage:
        return cls(
            script_id=runtime.ScriptId.from_json(json['scriptId']),
            url=json['url'],
            functions=[FunctionCoverage.from_json(i) for i in json['functions']],
        )


def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    yield {'method': 'Profiler.disable'}


def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    yield {'method': 'Profiler.enable'}


def get_best_effort_coverage() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[ScriptCoverage]]:
    '''Collect coverage data for the current isolate. The coverage data may be incomplete due to
    garbage collection.

    :returns: Coverage data for the current isolate.
    '''
    json = yield {'method': 'Profiler.getBestEffortCoverage'}
    return [ScriptCoverage.from_json(i) for i in json['result']]


def set_sampling_interval(interval: int) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Changes CPU profiler sampling interval. Must be called before CPU profiles recording started.

    :param interval: New sampling interval in microseconds.
    '''
    params: T_JSON_DICT = {}
    params['interval'] = interval
    yield {'method': 'Profiler.setSamplingInterval', 'params': params}


def start() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    yield {'method': 'Profiler.start'}


def start_precise_coverage(
        call_count: bool | None = None,
        detailed: bool | None = None,
        allow_triggered_updates: bool | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, float]:
    '''Enable precise code coverage. Coverage data for JavaScript executed before enabling precise code
    coverage may be incomplete. Enabling prevents running optimized code and resets execution
    counters.

    :param call_count: *(Optional)* Collect accurate call counts beyond simple 'covered' or 'not covered'.
    :param detailed: *(Optional)* Collect block-based coverage.
    :param allow_triggered_updates: *(Optional)* Allow the backend to send updates on its own initiative
    :returns: Monotonically increasing time (in seconds) when the coverage update was taken in the backend.
    '''
    params: T_JSON_DICT = {}
    if call_count is not None:
        params['callCount'] = call_count
    if detailed is not None:
        params['detailed'] = detailed
    if allow_triggered_updates is not None:
        params['allowTriggeredUpdates'] = allow_triggered_updates
    json = yield {'method': 'Profiler.startPreciseCoverage', 'params': params}
    return float(json['timestamp'])


def stop() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, Profile]:
    ''':returns: Recorded profile.'''
    json = yield {'method': 'Profiler.stop'}
    return Profile.from_json(json['profile'])


def stop_precise_coverage() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Disable precise code coverage. Disabling releases unnecessary execution count records and allows
    executing optimized code.
    '''
    yield {'method': 'Profiler.stopPreciseCoverage'}


def take_precise_coverage() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, tuple[list[ScriptCoverage], float]]:
    '''Collect coverage data for the current isolate, and resets execution counters. Precise code
    coverage needs to have started.

    :returns: A tuple with the following items:
        0. **result** — Coverage data for the current isolate.
        1. **timestamp** — Monotonically increasing time (in seconds) when the coverage update was taken in the backend.
    '''
    json = yield {'method': 'Profiler.takePreciseCoverage'}
    return (
        [ScriptCoverage.from_json(i) for i in json['result']],
        float(json['timestamp']),
    )


@event_class('Profiler.consoleProfileFinished')
@dataclass(slots=True)
class ConsoleProfileFinished:
    id: str
    #: Location of console.profileEnd().
    location: debugger.Location
    profile: Profile
    #: *(Optional)* Profile title passed as an argument to console.profile().
    title: str | None = None

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ConsoleProfileFinished:
        return cls(
            id=json['id'],
            location=debugger.Location.from_json(json['location']),
            profile=Profile.from_json(json['profile']),
            title=json['title'] if json.get('title') is not None else None,
        )


@event_class('Profiler.consoleProfileStarted')
@dataclass(slots=True)
class ConsoleProfileStarted:
    '''Sent when new profile recording is started using console.profile() call.'''
    id: str
    #: Location of console.profile().
    location: debugger.Location
    #: *(Optional)* Profile title passed as an argument to console.profile().
    title: str | None = None

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ConsoleProfileStarted:
        return cls(
            id=json['id'],
            location=debugger.Location.from_json(json['location']),
            title=json['title'] if json.get('title') is not None else None,
        )


@event_class('Profiler.preciseCoverageDeltaUpdate')
@dataclass(slots=True)
class PreciseCoverageDeltaUpdate:
    '''Reports coverage delta since the last poll (either from an event like this, or from
    `takePreciseCoverage` for the current isolate. May only be sent if precise code
    coverage has been started. This event can be trigged by the embedder to, for example,
    trigger collection of coverage data immediately at a certain point in time.

    **EXPERIMENTAL**
    '''
    #: Monotonically increasing time (in seconds) when the coverage update was taken in the backend.
    timestamp: float
    #: Identifier for distinguishing coverage events.
    occasion: str
    #: Coverage data for the current isolate.
    result: list[ScriptCoverage]

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PreciseCoverageDeltaUpdate:
        return cls(
            timestamp=float(json['timestamp']),
            occasion=json['occasion'],
            result=[ScriptCoverage.from_json(i) for i in json['result']],
        )
