# DO NOT EDIT — generated by purecdp._generator from ServiceWorker (devtools-protocol 3bd8f01934b5)
'''CDP domain: ServiceWorker.

**EXPERIMENTAL**
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class

from . import target


class RegistrationID(str):
    def to_json(self) -> str:
        return str(self)

    @classmethod
    def from_json(cls, json: str) -> RegistrationID:
        return cls(json)

    def __repr__(self) -> str:
        return f'RegistrationID({str.__repr__(self)})'


@dataclass(slots=True)
class ServiceWorkerRegistration:
    '''ServiceWorker registration.'''
    registration_id: RegistrationID
    scope_url: str
    is_deleted: bool

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['registrationId'] = self.registration_id.to_json()
        json['scopeURL'] = self.scope_url
        json['isDeleted'] = self.is_deleted
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ServiceWorkerRegistration:
        return cls(
            registration_id=RegistrationID.from_json(json['registrationId']),
            scope_url=json['scopeURL'],
            is_deleted=json['isDeleted'],
        )


class ServiceWorkerVersionRunningStatus(enum.StrEnum):
    STOPPED = 'stopped'
    STARTING = 'starting'
    RUNNING = 'running'
    STOPPING = 'stopping'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> ServiceWorkerVersionRunningStatus:
        return cls(json)


class ServiceWorkerVersionStatus(enum.StrEnum):
    NEW = 'new'
    INSTALLING = 'installing'
    INSTALLED = 'installed'
    ACTIVATING = 'activating'
    ACTIVATED = 'activated'
    REDUNDANT = 'redundant'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> ServiceWorkerVersionStatus:
        return cls(json)


@dataclass(slots=True)
class ServiceWorkerVersion:
    '''ServiceWorker version.'''
    version_id: str
    registration_id: RegistrationID
    script_url: str
    running_status: ServiceWorkerVersionRunningStatus
    status: ServiceWorkerVersionStatus
    #: *(Optional)* The Last-Modified header value of the main script.
    script_last_modified: float | None = None
    #: *(Optional)* The time at which the response headers of the main script were received from the server. For cached script it is the last time the cache entry was validated.
    script_response_time: float | None = None
    #: *(Optional)*
    controlled_clients: list[target.TargetID] | None = None
    #: *(Optional)*
    target_id: target.TargetID | None = None
    #: *(Optional)*
    router_rules: str | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['versionId'] = self.version_id
        json['registrationId'] = self.registration_id.to_json()
        json['scriptURL'] = self.script_url
        json['runningStatus'] = self.running_status.to_json()
        json['status'] = self.status.to_json()
        if self.script_last_modified is not None:
            json['scriptLastModified'] = self.script_last_modified
        if self.script_response_time is not None:
            json['scriptResponseTime'] = self.script_response_time
        if self.controlled_clients is not None:
            json['controlledClients'] = [i.to_json() for i in self.controlled_clients]
        if self.target_id is not None:
            json['targetId'] = self.target_id.to_json()
        if self.router_rules is not None:
            json['routerRules'] = self.router_rules
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ServiceWorkerVersion:
        return cls(
            version_id=json['versionId'],
            registration_id=RegistrationID.from_json(json['registrationId']),
            script_url=json['scriptURL'],
            running_status=ServiceWorkerVersionRunningStatus.from_json(json['runningStatus']),
            status=ServiceWorkerVersionStatus.from_json(json['status']),
            script_last_modified=float(json['scriptLastModified']) if json.get('scriptLastModified') is not None else None,
            script_response_time=float(json['scriptResponseTime']) if json.get('scriptResponseTime') is not None else None,
            controlled_clients=[target.TargetID.from_json(i) for i in json['controlledClients']] if json.get('controlledClients') is not None else None,
            target_id=target.TargetID.from_json(json['targetId']) if json.get('targetId') is not None else None,
            router_rules=json['routerRules'] if json.get('routerRules') is not None else None,
        )


@dataclass(slots=True)
class ServiceWorkerErrorMessage:
    '''ServiceWorker error message.'''
    error_message: str
    registration_id: RegistrationID
    version_id: str
    source_url: str
    line_number: int
    column_number: int

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['errorMessage'] = self.error_message
        json['registrationId'] = self.registration_id.to_json()
        json['versionId'] = self.version_id
        json['sourceURL'] = self.source_url
        json['lineNumber'] = self.line_number
        json['columnNumber'] = self.column_number
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ServiceWorkerErrorMessage:
        return cls(
            error_message=json['errorMessage'],
            registration_id=RegistrationID.from_json(json['registrationId']),
            version_id=json['versionId'],
            source_url=json['sourceURL'],
            line_number=json['lineNumber'],
            column_number=json['columnNumber'],
        )


def deliver_push_message(
        origin: str,
        registration_id: RegistrationID,
        data: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    ''':param origin: 
    :param registration_id:
    :param data:
    '''
    params: T_JSON_DICT = {}
    params['origin'] = origin
    params['registrationId'] = registration_id.to_json()
    params['data'] = data
    yield {'method': 'ServiceWorker.deliverPushMessage', 'params': params}


def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    yield {'method': 'ServiceWorker.disable'}


def dispatch_sync_event(
        origin: str,
        registration_id: RegistrationID,
        tag: str,
        last_chance: bool,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    ''':param origin: 
    :param registration_id:
    :param tag:
    :param last_chance:
    '''
    params: T_JSON_DICT = {}
    params['origin'] = origin
    params['registrationId'] = registration_id.to_json()
    params['tag'] = tag
    params['lastChance'] = last_chance
    yield {'method': 'ServiceWorker.dispatchSyncEvent', 'params': params}


def dispatch_periodic_sync_event(
        origin: str,
        registration_id: RegistrationID,
        tag: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    ''':param origin: 
    :param registration_id:
    :param tag:
    '''
    params: T_JSON_DICT = {}
    params['origin'] = origin
    params['registrationId'] = registration_id.to_json()
    params['tag'] = tag
    yield {'method': 'ServiceWorker.dispatchPeriodicSyncEvent', 'params': params}


def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    yield {'method': 'ServiceWorker.enable'}


def set_force_update_on_page_load(
        force_update_on_page_load: bool,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    ''':param force_update_on_page_load: '''
    params: T_JSON_DICT = {}
    params['forceUpdateOnPageLoad'] = force_update_on_page_load
    yield {'method': 'ServiceWorker.setForceUpdateOnPageLoad', 'params': params}


def skip_waiting(scope_url: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    ''':param scope_url: '''
    params: T_JSON_DICT = {}
    params['scopeURL'] = scope_url
    yield {'method': 'ServiceWorker.skipWaiting', 'params': params}


def start_worker(scope_url: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    ''':param scope_url: '''
    params: T_JSON_DICT = {}
    params['scopeURL'] = scope_url
    yield {'method': 'ServiceWorker.startWorker', 'params': params}


def stop_all_workers() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    yield {'method': 'ServiceWorker.stopAllWorkers'}


def stop_worker(version_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    ''':param version_id: '''
    params: T_JSON_DICT = {}
    params['versionId'] = version_id
    yield {'method': 'ServiceWorker.stopWorker', 'params': params}


def unregister(scope_url: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    ''':param scope_url: '''
    params: T_JSON_DICT = {}
    params['scopeURL'] = scope_url
    yield {'method': 'ServiceWorker.unregister', 'params': params}


def update_registration(scope_url: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    ''':param scope_url: '''
    params: T_JSON_DICT = {}
    params['scopeURL'] = scope_url
    yield {'method': 'ServiceWorker.updateRegistration', 'params': params}


@event_class('ServiceWorker.workerErrorReported')
@dataclass(slots=True)
class WorkerErrorReported:
    error_message: ServiceWorkerErrorMessage

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WorkerErrorReported:
        return cls(
            error_message=ServiceWorkerErrorMessage.from_json(json['errorMessage']),
        )


@event_class('ServiceWorker.workerRegistrationUpdated')
@dataclass(slots=True)
class WorkerRegistrationUpdated:
    registrations: list[ServiceWorkerRegistration]

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WorkerRegistrationUpdated:
        return cls(
            registrations=[ServiceWorkerRegistration.from_json(i) for i in json['registrations']],
        )


@event_class('ServiceWorker.workerVersionUpdated')
@dataclass(slots=True)
class WorkerVersionUpdated:
    versions: list[ServiceWorkerVersion]

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WorkerVersionUpdated:
        return cls(
            versions=[ServiceWorkerVersion.from_json(i) for i in json['versions']],
        )
