# DO NOT EDIT — generated by purecdp._generator from Storage (devtools-protocol 3bd8f01934b5)
'''CDP domain: Storage.

**EXPERIMENTAL**
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class

from . import browser, network, page, target


class SerializedStorageKey(str):
    def to_json(self) -> str:
        return str(self)

    @classmethod
    def from_json(cls, json: str) -> SerializedStorageKey:
        return cls(json)

    def __repr__(self) -> str:
        return f'SerializedStorageKey({str.__repr__(self)})'


class StorageType(enum.StrEnum):
    '''Enum of possible storage types.'''
    COOKIES = 'cookies'
    FILE_SYSTEMS = 'file_systems'
    INDEXEDDB = 'indexeddb'
    LOCAL_STORAGE = 'local_storage'
    SHADER_CACHE = 'shader_cache'
    WEBSQL = 'websql'
    SERVICE_WORKERS = 'service_workers'
    CACHE_STORAGE = 'cache_storage'
    INTEREST_GROUPS = 'interest_groups'
    SHARED_STORAGE = 'shared_storage'
    STORAGE_BUCKETS = 'storage_buckets'
    ALL = 'all'
    OTHER = 'other'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> StorageType:
        return cls(json)


@dataclass(slots=True)
class UsageForType:
    '''Usage for a storage type.'''
    #: Name of storage type.
    storage_type: StorageType
    #: Storage usage (bytes).
    usage: float

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['storageType'] = self.storage_type.to_json()
        json['usage'] = self.usage
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> UsageForType:
        return cls(
            storage_type=StorageType.from_json(json['storageType']),
            usage=float(json['usage']),
        )


@dataclass(slots=True)
class TrustTokens:
    '''Pair of issuer origin and number of available (signed, but not used) Trust
    Tokens from that issuer.

    **EXPERIMENTAL**
    '''
    issuer_origin: str
    count: float

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['issuerOrigin'] = self.issuer_origin
        json['count'] = self.count
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TrustTokens:
        return cls(
            issuer_origin=json['issuerOrigin'],
            count=float(json['count']),
        )


class SharedStorageAccessScope(enum.StrEnum):
    '''Enum of shared storage access scopes.'''
    WINDOW = 'window'
    SHARED_STORAGE_WORKLET = 'sharedStorageWorklet'
    HEADER = 'header'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> SharedStorageAccessScope:
        return cls(json)


class SharedStorageAccessMethod(enum.StrEnum):
    '''Enum of shared storage access methods.'''
    ADD_MODULE = 'addModule'
    CREATE_WORKLET = 'createWorklet'
    SELECT_URL = 'selectURL'
    RUN = 'run'
    BATCH_UPDATE = 'batchUpdate'
    SET = 'set'
    APPEND = 'append'
    DELETE = 'delete'
    CLEAR = 'clear'
    GET = 'get'
    KEYS = 'keys'
    VALUES = 'values'
    ENTRIES = 'entries'
    LENGTH = 'length'
    REMAINING_BUDGET = 'remainingBudget'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> SharedStorageAccessMethod:
        return cls(json)


@dataclass(slots=True)
class SharedStorageEntry:
    '''Struct for a single key-value pair in an origin's shared storage.'''
    key: str
    value: str

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['key'] = self.key
        json['value'] = self.value
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStorageEntry:
        return cls(
            key=json['key'],
            value=json['value'],
        )


@dataclass(slots=True)
class SharedStorageMetadata:
    '''Details for an origin's shared storage.'''
    #: Time when the origin's shared storage was last created.
    creation_time: network.TimeSinceEpoch
    #: Number of key-value pairs stored in origin's shared storage.
    length: int
    #: Current amount of bits of entropy remaining in the navigation budget.
    remaining_budget: float
    #: Total number of bytes stored as key-value pairs in origin's shared storage.
    bytes_used: int

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['creationTime'] = self.creation_time.to_json()
        json['length'] = self.length
        json['remainingBudget'] = self.remaining_budget
        json['bytesUsed'] = self.bytes_used
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStorageMetadata:
        return cls(
            creation_time=network.TimeSinceEpoch.from_json(json['creationTime']),
            length=json['length'],
            remaining_budget=float(json['remainingBudget']),
            bytes_used=json['bytesUsed'],
        )


@dataclass(slots=True)
class SharedStoragePrivateAggregationConfig:
    '''Represents a dictionary object passed in as privateAggregationConfig to
    run or selectURL.
    '''
    #: Configures the maximum size allowed for filtering IDs.
    filtering_id_max_bytes: int
    #: *(Optional)* The chosen aggregation service deployment.
    aggregation_coordinator_origin: str | None = None
    #: *(Optional)* The context ID provided.
    context_id: str | None = None
    #: *(Optional)* The limit on the number of contributions in the final report.
    max_contributions: int | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['filteringIdMaxBytes'] = self.filtering_id_max_bytes
        if self.aggregation_coordinator_origin is not None:
            json['aggregationCoordinatorOrigin'] = self.aggregation_coordinator_origin
        if self.context_id is not None:
            json['contextId'] = self.context_id
        if self.max_contributions is not None:
            json['maxContributions'] = self.max_contributions
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStoragePrivateAggregationConfig:
        return cls(
            filtering_id_max_bytes=json['filteringIdMaxBytes'],
            aggregation_coordinator_origin=json['aggregationCoordinatorOrigin'] if json.get('aggregationCoordinatorOrigin') is not None else None,
            context_id=json['contextId'] if json.get('contextId') is not None else None,
            max_contributions=json['maxContributions'] if json.get('maxContributions') is not None else None,
        )


@dataclass(slots=True)
class SharedStorageReportingMetadata:
    '''Pair of reporting metadata details for a candidate URL for `selectURL()`.'''
    event_type: str
    reporting_url: str

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['eventType'] = self.event_type
        json['reportingUrl'] = self.reporting_url
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStorageReportingMetadata:
        return cls(
            event_type=json['eventType'],
            reporting_url=json['reportingUrl'],
        )


@dataclass(slots=True)
class SharedStorageUrlWithMetadata:
    '''Bundles a candidate URL with its reporting metadata.'''
    #: Spec of candidate URL.
    url: str
    #: Any associated reporting metadata.
    reporting_metadata: list[SharedStorageReportingMetadata]

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['url'] = self.url
        json['reportingMetadata'] = [i.to_json() for i in self.reporting_metadata]
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStorageUrlWithMetadata:
        return cls(
            url=json['url'],
            reporting_metadata=[SharedStorageReportingMetadata.from_json(i) for i in json['reportingMetadata']],
        )


@dataclass(slots=True)
class SharedStorageAccessParams:
    '''Bundles the parameters for shared storage access events whose
    presence/absence can vary according to SharedStorageAccessType.
    '''
    #: *(Optional)* Spec of the module script URL. Present only for SharedStorageAccessMethods: addModule and createWorklet.
    script_source_url: str | None = None
    #: *(Optional)* String denoting "context-origin", "script-origin", or a custom origin to be used as the worklet's data origin. Present only for SharedStorageAccessMethod: createWorklet.
    data_origin: str | None = None
    #: *(Optional)* Name of the registered operation to be run. Present only for SharedStorageAccessMethods: run and selectURL.
    operation_name: str | None = None
    #: *(Optional)* ID of the operation call. Present only for SharedStorageAccessMethods: run and selectURL.
    operation_id: str | None = None
    #: *(Optional)* Whether or not to keep the worket alive for future run or selectURL calls. Present only for SharedStorageAccessMethods: run and selectURL.
    keep_alive: bool | None = None
    #: *(Optional)* Configures the private aggregation options. Present only for SharedStorageAccessMethods: run and selectURL.
    private_aggregation_config: SharedStoragePrivateAggregationConfig | None = None
    #: *(Optional)* The operation's serialized data in bytes (converted to a string). Present only for SharedStorageAccessMethods: run and selectURL. TODO(crbug.com/401011862): Consider updating this parameter to binary.
    serialized_data: str | None = None
    #: *(Optional)* Array of candidate URLs' specs, along with any associated metadata. Present only for SharedStorageAccessMethod: selectURL.
    urls_with_metadata: list[SharedStorageUrlWithMetadata] | None = None
    #: *(Optional)* Spec of the URN:UUID generated for a selectURL call. Present only for SharedStorageAccessMethod: selectURL.
    urn_uuid: str | None = None
    #: *(Optional)* Key for a specific entry in an origin's shared storage. Present only for SharedStorageAccessMethods: set, append, delete, and get.
    key: str | None = None
    #: *(Optional)* Value for a specific entry in an origin's shared storage. Present only for SharedStorageAccessMethods: set and append.
    value: str | None = None
    #: *(Optional)* Whether or not to set an entry for a key if that key is already present. Present only for SharedStorageAccessMethod: set.
    ignore_if_present: bool | None = None
    #: *(Optional)* A number denoting the (0-based) order of the worklet's creation relative to all other shared storage worklets created by documents using the current storage partition. Present only for SharedStorageAccessMethods: addModule, createWorklet.
    worklet_ordinal: int | None = None
    #: *(Optional)* Hex representation of the DevTools token used as the TargetID for the associated shared storage worklet. Present only for SharedStorageAccessMethods: addModule, createWorklet, run, selectURL, and any other SharedStorageAccessMethod when the SharedStorageAccessScope is sharedStorageWorklet.
    worklet_target_id: target.TargetID | None = None
    #: *(Optional)* Name of the lock to be acquired, if present. Optionally present only for SharedStorageAccessMethods: batchUpdate, set, append, delete, and clear.
    with_lock: str | None = None
    #: *(Optional)* If the method has been called as part of a batchUpdate, then this number identifies the batch to which it belongs. Optionally present only for SharedStorageAccessMethods: batchUpdate (required), set, append, delete, and clear.
    batch_update_id: str | None = None
    #: *(Optional)* Number of modifier methods sent in batch. Present only for SharedStorageAccessMethod: batchUpdate.
    batch_size: int | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        if self.script_source_url is not None:
            json['scriptSourceUrl'] = self.script_source_url
        if self.data_origin is not None:
            json['dataOrigin'] = self.data_origin
        if self.operation_name is not None:
            json['operationName'] = self.operation_name
        if self.operation_id is not None:
            json['operationId'] = self.operation_id
        if self.keep_alive is not None:
            json['keepAlive'] = self.keep_alive
        if self.private_aggregation_config is not None:
            json['privateAggregationConfig'] = self.private_aggregation_config.to_json()
        if self.serialized_data is not None:
            json['serializedData'] = self.serialized_data
        if self.urls_with_metadata is not None:
            json['urlsWithMetadata'] = [i.to_json() for i in self.urls_with_metadata]
        if self.urn_uuid is not None:
            json['urnUuid'] = self.urn_uuid
        if self.key is not None:
            json['key'] = self.key
        if self.value is not None:
            json['value'] = self.value
        if self.ignore_if_present is not None:
            json['ignoreIfPresent'] = self.ignore_if_present
        if self.worklet_ordinal is not None:
            json['workletOrdinal'] = self.worklet_ordinal
        if self.worklet_target_id is not None:
            json['workletTargetId'] = self.worklet_target_id.to_json()
        if self.with_lock is not None:
            json['withLock'] = self.with_lock
        if self.batch_update_id is not None:
            json['batchUpdateId'] = self.batch_update_id
        if self.batch_size is not None:
            json['batchSize'] = self.batch_size
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStorageAccessParams:
        return cls(
            script_source_url=json['scriptSourceUrl'] if json.get('scriptSourceUrl') is not None else None,
            data_origin=json['dataOrigin'] if json.get('dataOrigin') is not None else None,
            operation_name=json['operationName'] if json.get('operationName') is not None else None,
            operation_id=json['operationId'] if json.get('operationId') is not None else None,
            keep_alive=json['keepAlive'] if json.get('keepAlive') is not None else None,
            private_aggregation_config=SharedStoragePrivateAggregationConfig.from_json(json['privateAggregationConfig']) if json.get('privateAggregationConfig') is not None else None,
            serialized_data=json['serializedData'] if json.get('serializedData') is not None else None,
            urls_with_metadata=[SharedStorageUrlWithMetadata.from_json(i) for i in json['urlsWithMetadata']] if json.get('urlsWithMetadata') is not None else None,
            urn_uuid=json['urnUuid'] if json.get('urnUuid') is not None else None,
            key=json['key'] if json.get('key') is not None else None,
            value=json['value'] if json.get('value') is not None else None,
            ignore_if_present=json['ignoreIfPresent'] if json.get('ignoreIfPresent') is not None else None,
            worklet_ordinal=json['workletOrdinal'] if json.get('workletOrdinal') is not None else None,
            worklet_target_id=target.TargetID.from_json(json['workletTargetId']) if json.get('workletTargetId') is not None else None,
            with_lock=json['withLock'] if json.get('withLock') is not None else None,
            batch_update_id=json['batchUpdateId'] if json.get('batchUpdateId') is not None else None,
            batch_size=json['batchSize'] if json.get('batchSize') is not None else None,
        )


class StorageBucketsDurability(enum.StrEnum):
    RELAXED = 'relaxed'
    STRICT = 'strict'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> StorageBucketsDurability:
        return cls(json)


@dataclass(slots=True)
class StorageBucket:
    storage_key: SerializedStorageKey
    #: *(Optional)* If not specified, it is the default bucket of the storageKey.
    name: str | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['storageKey'] = self.storage_key.to_json()
        if self.name is not None:
            json['name'] = self.name
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> StorageBucket:
        return cls(
            storage_key=SerializedStorageKey.from_json(json['storageKey']),
            name=json['name'] if json.get('name') is not None else None,
        )


@dataclass(slots=True)
class StorageBucketInfo:
    bucket: StorageBucket
    id: str
    expiration: network.TimeSinceEpoch
    #: Storage quota (bytes).
    quota: float
    persistent: bool
    durability: StorageBucketsDurability

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['bucket'] = self.bucket.to_json()
        json['id'] = self.id
        json['expiration'] = self.expiration.to_json()
        json['quota'] = self.quota
        json['persistent'] = self.persistent
        json['durability'] = self.durability.to_json()
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> StorageBucketInfo:
        return cls(
            bucket=StorageBucket.from_json(json['bucket']),
            id=json['id'],
            expiration=network.TimeSinceEpoch.from_json(json['expiration']),
            quota=float(json['quota']),
            persistent=json['persistent'],
            durability=StorageBucketsDurability.from_json(json['durability']),
        )


@dataclass(slots=True)
class RelatedWebsiteSet:
    '''A single Related Website Set object.

    **EXPERIMENTAL**
    '''
    #: The primary site of this set, along with the ccTLDs if there is any.
    primary_sites: list[str]
    #: The associated sites of this set, along with the ccTLDs if there is any.
    associated_sites: list[str]
    #: The service sites of this set, along with the ccTLDs if there is any.
    service_sites: list[str]

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['primarySites'] = list(self.primary_sites)
        json['associatedSites'] = list(self.associated_sites)
        json['serviceSites'] = list(self.service_sites)
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RelatedWebsiteSet:
        return cls(
            primary_sites=list(json['primarySites']),
            associated_sites=list(json['associatedSites']),
            service_sites=list(json['serviceSites']),
        )


def get_storage_key_for_frame(
        frame_id: page.FrameId,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SerializedStorageKey]:
    '''Returns a storage key given a frame id.
    Deprecated. Please use Storage.getStorageKey instead.

    **DEPRECATED**

    :param frame_id:
    :returns:
    '''
    params: T_JSON_DICT = {}
    params['frameId'] = frame_id.to_json()
    json = yield {'method': 'Storage.getStorageKeyForFrame', 'params': params}
    return SerializedStorageKey.from_json(json['storageKey'])


def get_storage_key(
        frame_id: page.FrameId | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SerializedStorageKey]:
    '''Returns storage key for the given frame. If no frame ID is provided,
    the storage key of the target executing this command is returned.

    **EXPERIMENTAL**

    :param frame_id: *(Optional)*
    :returns:
    '''
    params: T_JSON_DICT = {}
    if frame_id is not None:
        params['frameId'] = frame_id.to_json()
    json = yield {'method': 'Storage.getStorageKey', 'params': params}
    return SerializedStorageKey.from_json(json['storageKey'])


def clear_data_for_origin(
        origin: str,
        storage_types: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Clears storage for origin.

    :param origin: Security origin.
    :param storage_types: Comma separated list of StorageType to clear.
    '''
    params: T_JSON_DICT = {}
    params['origin'] = origin
    params['storageTypes'] = storage_types
    yield {'method': 'Storage.clearDataForOrigin', 'params': params}


def clear_data_for_storage_key(
        storage_key: str,
        storage_types: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Clears storage for storage key.

    :param storage_key: Storage key.
    :param storage_types: Comma separated list of StorageType to clear.
    '''
    params: T_JSON_DICT = {}
    params['storageKey'] = storage_key
    params['storageTypes'] = storage_types
    yield {'method': 'Storage.clearDataForStorageKey', 'params': params}


def get_cookies(
        browser_context_id: browser.BrowserContextID | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[network.Cookie]]:
    '''Returns all browser cookies.

    :param browser_context_id: *(Optional)* Browser context to use when called on the browser endpoint.
    :returns: Array of cookie objects.
    '''
    params: T_JSON_DICT = {}
    if browser_context_id is not None:
        params['browserContextId'] = browser_context_id.to_json()
    json = yield {'method': 'Storage.getCookies', 'params': params}
    return [network.Cookie.from_json(i) for i in json['cookies']]


def set_cookies(
        cookies: list[network.CookieParam],
        browser_context_id: browser.BrowserContextID | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Sets given cookies.

    :param cookies: Cookies to be set.
    :param browser_context_id: *(Optional)* Browser context to use when called on the browser endpoint.
    '''
    params: T_JSON_DICT = {}
    params['cookies'] = [i.to_json() for i in cookies]
    if browser_context_id is not None:
        params['browserContextId'] = browser_context_id.to_json()
    yield {'method': 'Storage.setCookies', 'params': params}


def clear_cookies(
        browser_context_id: browser.BrowserContextID | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Clears cookies.

    :param browser_context_id: *(Optional)* Browser context to use when called on the browser endpoint.
    '''
    params: T_JSON_DICT = {}
    if browser_context_id is not None:
        params['browserContextId'] = browser_context_id.to_json()
    yield {'method': 'Storage.clearCookies', 'params': params}


def get_usage_and_quota(
        origin: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, tuple[float, float, bool, list[UsageForType]]]:
    '''Returns usage and quota in bytes.

    :param origin: Security origin.
    :returns: A tuple with the following items:
        0. **usage** — Storage usage (bytes).
        1. **quota** — Storage quota (bytes).
        2. **overrideActive** — Whether or not the origin has an active storage quota override
        3. **usageBreakdown** — Storage usage per type (bytes).
    '''
    params: T_JSON_DICT = {}
    params['origin'] = origin
    json = yield {'method': 'Storage.getUsageAndQuota', 'params': params}
    return (
        float(json['usage']),
        float(json['quota']),
        json['overrideActive'],
        [UsageForType.from_json(i) for i in json['usageBreakdown']],
    )


def override_quota_for_origin(
        origin: str,
        quota_size: float | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Override quota for the specified origin

    **EXPERIMENTAL**

    :param origin: Security origin.
    :param quota_size: *(Optional)* The quota size (in bytes) to override the original quota with. If this is called multiple times, the overridden quota will be equal to the quotaSize provided in the final call. If this is called without specifying a quotaSize, the quota will be reset to the default value for the specified origin. If this is called multiple times with different origins, the override will be maintained for each origin until it is disabled (called without a quotaSize).
    '''
    params: T_JSON_DICT = {}
    params['origin'] = origin
    if quota_size is not None:
        params['quotaSize'] = quota_size
    yield {'method': 'Storage.overrideQuotaForOrigin', 'params': params}


def track_cache_storage_for_origin(origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Registers origin to be notified when an update occurs to its cache storage list.

    :param origin: Security origin.
    '''
    params: T_JSON_DICT = {}
    params['origin'] = origin
    yield {'method': 'Storage.trackCacheStorageForOrigin', 'params': params}


def track_cache_storage_for_storage_key(
        storage_key: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Registers storage key to be notified when an update occurs to its cache storage list.

    :param storage_key: Storage key.
    '''
    params: T_JSON_DICT = {}
    params['storageKey'] = storage_key
    yield {'method': 'Storage.trackCacheStorageForStorageKey', 'params': params}


def track_indexed_db_for_origin(origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Registers origin to be notified when an update occurs to its IndexedDB.

    :param origin: Security origin.
    '''
    params: T_JSON_DICT = {}
    params['origin'] = origin
    yield {'method': 'Storage.trackIndexedDBForOrigin', 'params': params}


def track_indexed_db_for_storage_key(
        storage_key: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Registers storage key to be notified when an update occurs to its IndexedDB.

    :param storage_key: Storage key.
    '''
    params: T_JSON_DICT = {}
    params['storageKey'] = storage_key
    yield {'method': 'Storage.trackIndexedDBForStorageKey', 'params': params}


def untrack_cache_storage_for_origin(
        origin: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Unregisters origin from receiving notifications for cache storage.

    :param origin: Security origin.
    '''
    params: T_JSON_DICT = {}
    params['origin'] = origin
    yield {'method': 'Storage.untrackCacheStorageForOrigin', 'params': params}


def untrack_cache_storage_for_storage_key(
        storage_key: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Unregisters storage key from receiving notifications for cache storage.

    :param storage_key: Storage key.
    '''
    params: T_JSON_DICT = {}
    params['storageKey'] = storage_key
    yield {'method': 'Storage.untrackCacheStorageForStorageKey', 'params': params}


def untrack_indexed_db_for_origin(origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Unregisters origin from receiving notifications for IndexedDB.

    :param origin: Security origin.
    '''
    params: T_JSON_DICT = {}
    params['origin'] = origin
    yield {'method': 'Storage.untrackIndexedDBForOrigin', 'params': params}


def untrack_indexed_db_for_storage_key(
        storage_key: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Unregisters storage key from receiving notifications for IndexedDB.

    :param storage_key: Storage key.
    '''
    params: T_JSON_DICT = {}
    params['storageKey'] = storage_key
    yield {'method': 'Storage.untrackIndexedDBForStorageKey', 'params': params}


def get_trust_tokens() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[TrustTokens]]:
    '''Returns the number of stored Trust Tokens per issuer for the
    current browsing context.

    **EXPERIMENTAL**

    :returns:
    '''
    json = yield {'method': 'Storage.getTrustTokens'}
    return [TrustTokens.from_json(i) for i in json['tokens']]


def clear_trust_tokens(issuer_origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, bool]:
    '''Removes all Trust Tokens issued by the provided issuerOrigin.
    Leaves other stored data, including the issuer's Redemption Records, intact.

    **EXPERIMENTAL**

    :param issuer_origin:
    :returns: True if any tokens were deleted, false otherwise.
    '''
    params: T_JSON_DICT = {}
    params['issuerOrigin'] = issuer_origin
    json = yield {'method': 'Storage.clearTrustTokens', 'params': params}
    return json['didDeleteTokens']


def get_shared_storage_metadata(
        owner_origin: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SharedStorageMetadata]:
    '''Gets metadata for an origin's shared storage.

    **EXPERIMENTAL**

    :param owner_origin:
    :returns:
    '''
    params: T_JSON_DICT = {}
    params['ownerOrigin'] = owner_origin
    json = yield {'method': 'Storage.getSharedStorageMetadata', 'params': params}
    return SharedStorageMetadata.from_json(json['metadata'])


def get_shared_storage_entries(
        owner_origin: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[SharedStorageEntry]]:
    '''Gets the entries in an given origin's shared storage.

    **EXPERIMENTAL**

    :param owner_origin:
    :returns:
    '''
    params: T_JSON_DICT = {}
    params['ownerOrigin'] = owner_origin
    json = yield {'method': 'Storage.getSharedStorageEntries', 'params': params}
    return [SharedStorageEntry.from_json(i) for i in json['entries']]


def set_shared_storage_entry(
        owner_origin: str,
        key: str,
        value: str,
        ignore_if_present: bool | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Sets entry with `key` and `value` for a given origin's shared storage.

    **EXPERIMENTAL**

    :param owner_origin:
    :param key:
    :param value:
    :param ignore_if_present: *(Optional)* If `ignoreIfPresent` is included and true, then only sets the entry if `key` doesn't already exist.
    '''
    params: T_JSON_DICT = {}
    params['ownerOrigin'] = owner_origin
    params['key'] = key
    params['value'] = value
    if ignore_if_present is not None:
        params['ignoreIfPresent'] = ignore_if_present
    yield {'method': 'Storage.setSharedStorageEntry', 'params': params}


def delete_shared_storage_entry(
        owner_origin: str,
        key: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Deletes entry for `key` (if it exists) for a given origin's shared storage.

    **EXPERIMENTAL**

    :param owner_origin:
    :param key:
    '''
    params: T_JSON_DICT = {}
    params['ownerOrigin'] = owner_origin
    params['key'] = key
    yield {'method': 'Storage.deleteSharedStorageEntry', 'params': params}


def clear_shared_storage_entries(
        owner_origin: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Clears all entries for a given origin's shared storage.

    **EXPERIMENTAL**

    :param owner_origin:
    '''
    params: T_JSON_DICT = {}
    params['ownerOrigin'] = owner_origin
    yield {'method': 'Storage.clearSharedStorageEntries', 'params': params}


def reset_shared_storage_budget(
        owner_origin: str,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Resets the budget for `ownerOrigin` by clearing all budget withdrawals.

    **EXPERIMENTAL**

    :param owner_origin:
    '''
    params: T_JSON_DICT = {}
    params['ownerOrigin'] = owner_origin
    yield {'method': 'Storage.resetSharedStorageBudget', 'params': params}


def set_shared_storage_tracking(enable: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Enables/disables issuing of sharedStorageAccessed events.

    **EXPERIMENTAL**

    :param enable:
    '''
    params: T_JSON_DICT = {}
    params['enable'] = enable
    yield {'method': 'Storage.setSharedStorageTracking', 'params': params}


def set_storage_bucket_tracking(
        storage_key: str,
        enable: bool,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Set tracking for a storage key's buckets.

    **EXPERIMENTAL**

    :param storage_key:
    :param enable:
    '''
    params: T_JSON_DICT = {}
    params['storageKey'] = storage_key
    params['enable'] = enable
    yield {'method': 'Storage.setStorageBucketTracking', 'params': params}


def delete_storage_bucket(
        bucket: StorageBucket,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Deletes the Storage Bucket with the given storage key and bucket name.

    **EXPERIMENTAL**

    :param bucket:
    '''
    params: T_JSON_DICT = {}
    params['bucket'] = bucket.to_json()
    yield {'method': 'Storage.deleteStorageBucket', 'params': params}


def run_bounce_tracking_mitigations() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[str]]:
    '''Deletes state for sites identified as potential bounce trackers, immediately.

    **EXPERIMENTAL**

    :returns:
    '''
    json = yield {'method': 'Storage.runBounceTrackingMitigations'}
    return list(json['deletedSites'])


def get_related_website_sets() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[RelatedWebsiteSet]]:
    '''Returns the effective Related Website Sets in use by this profile for the browser
    session. The effective Related Website Sets will not change during a browser session.

    **EXPERIMENTAL**

    :returns:
    '''
    json = yield {'method': 'Storage.getRelatedWebsiteSets'}
    return [RelatedWebsiteSet.from_json(i) for i in json['sets']]


@event_class('Storage.cacheStorageContentUpdated')
@dataclass(slots=True)
class CacheStorageContentUpdated:
    '''A cache's contents have been modified.'''
    #: Origin to update.
    origin: str
    #: Storage key to update.
    storage_key: str
    #: Storage bucket to update.
    bucket_id: str
    #: Name of cache in origin.
    cache_name: str

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CacheStorageContentUpdated:
        return cls(
            origin=json['origin'],
            storage_key=json['storageKey'],
            bucket_id=json['bucketId'],
            cache_name=json['cacheName'],
        )


@event_class('Storage.cacheStorageListUpdated')
@dataclass(slots=True)
class CacheStorageListUpdated:
    '''A cache has been added/deleted.'''
    #: Origin to update.
    origin: str
    #: Storage key to update.
    storage_key: str
    #: Storage bucket to update.
    bucket_id: str

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CacheStorageListUpdated:
        return cls(
            origin=json['origin'],
            storage_key=json['storageKey'],
            bucket_id=json['bucketId'],
        )


@event_class('Storage.indexedDBContentUpdated')
@dataclass(slots=True)
class IndexedDBContentUpdated:
    '''The origin's IndexedDB object store has been modified.'''
    #: Origin to update.
    origin: str
    #: Storage key to update.
    storage_key: str
    #: Storage bucket to update.
    bucket_id: str
    #: Database to update.
    database_name: str
    #: ObjectStore to update.
    object_store_name: str

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> IndexedDBContentUpdated:
        return cls(
            origin=json['origin'],
            storage_key=json['storageKey'],
            bucket_id=json['bucketId'],
            database_name=json['databaseName'],
            object_store_name=json['objectStoreName'],
        )


@event_class('Storage.indexedDBListUpdated')
@dataclass(slots=True)
class IndexedDBListUpdated:
    '''The origin's IndexedDB database list has been modified.'''
    #: Origin to update.
    origin: str
    #: Storage key to update.
    storage_key: str
    #: Storage bucket to update.
    bucket_id: str

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> IndexedDBListUpdated:
        return cls(
            origin=json['origin'],
            storage_key=json['storageKey'],
            bucket_id=json['bucketId'],
        )


@event_class('Storage.sharedStorageAccessed')
@dataclass(slots=True)
class SharedStorageAccessed:
    '''Shared storage was accessed by the associated page.
    The following parameters are included in all events.
    '''
    #: Time of the access.
    access_time: network.TimeSinceEpoch
    #: Enum value indicating the access scope.
    scope: SharedStorageAccessScope
    #: Enum value indicating the Shared Storage API method invoked.
    method: SharedStorageAccessMethod
    #: DevTools Frame Token for the primary frame tree's root.
    main_frame_id: page.FrameId
    #: Serialization of the origin owning the Shared Storage data.
    owner_origin: str
    #: Serialization of the site owning the Shared Storage data.
    owner_site: str
    #: The sub-parameters wrapped by `params` are all optional and their presence/absence depends on `type`.
    params_: SharedStorageAccessParams

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStorageAccessed:
        return cls(
            access_time=network.TimeSinceEpoch.from_json(json['accessTime']),
            scope=SharedStorageAccessScope.from_json(json['scope']),
            method=SharedStorageAccessMethod.from_json(json['method']),
            main_frame_id=page.FrameId.from_json(json['mainFrameId']),
            owner_origin=json['ownerOrigin'],
            owner_site=json['ownerSite'],
            params_=SharedStorageAccessParams.from_json(json['params']),
        )


@event_class('Storage.sharedStorageWorkletOperationExecutionFinished')
@dataclass(slots=True)
class SharedStorageWorkletOperationExecutionFinished:
    '''A shared storage run or selectURL operation finished its execution.
    The following parameters are included in all events.
    '''
    #: Time that the operation finished.
    finished_time: network.TimeSinceEpoch
    #: Time, in microseconds, from start of shared storage JS API call until end of operation execution in the worklet.
    execution_time: int
    #: Enum value indicating the Shared Storage API method invoked.
    method: SharedStorageAccessMethod
    #: ID of the operation call.
    operation_id: str
    #: Hex representation of the DevTools token used as the TargetID for the associated shared storage worklet.
    worklet_target_id: target.TargetID
    #: DevTools Frame Token for the primary frame tree's root.
    main_frame_id: page.FrameId
    #: Serialization of the origin owning the Shared Storage data.
    owner_origin: str

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStorageWorkletOperationExecutionFinished:
        return cls(
            finished_time=network.TimeSinceEpoch.from_json(json['finishedTime']),
            execution_time=json['executionTime'],
            method=SharedStorageAccessMethod.from_json(json['method']),
            operation_id=json['operationId'],
            worklet_target_id=target.TargetID.from_json(json['workletTargetId']),
            main_frame_id=page.FrameId.from_json(json['mainFrameId']),
            owner_origin=json['ownerOrigin'],
        )


@event_class('Storage.storageBucketCreatedOrUpdated')
@dataclass(slots=True)
class StorageBucketCreatedOrUpdated:
    bucket_info: StorageBucketInfo

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> StorageBucketCreatedOrUpdated:
        return cls(
            bucket_info=StorageBucketInfo.from_json(json['bucketInfo']),
        )


@event_class('Storage.storageBucketDeleted')
@dataclass(slots=True)
class StorageBucketDeleted:
    bucket_id: str

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> StorageBucketDeleted:
        return cls(
            bucket_id=json['bucketId'],
        )
