# DO NOT EDIT — generated by purecdp._generator from Target (devtools-protocol 3bd8f01934b5)
'''CDP domain: Target.

Supports additional targets discovery and allows to attach to them.
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class

from . import browser, page


class TargetID(str):
    def to_json(self) -> str:
        return str(self)

    @classmethod
    def from_json(cls, json: str) -> TargetID:
        return cls(json)

    def __repr__(self) -> str:
        return f'TargetID({str.__repr__(self)})'


class SessionID(str):
    '''Unique identifier of attached debugging session.'''
    def to_json(self) -> str:
        return str(self)

    @classmethod
    def from_json(cls, json: str) -> SessionID:
        return cls(json)

    def __repr__(self) -> str:
        return f'SessionID({str.__repr__(self)})'


@dataclass(slots=True)
class TargetInfo:
    target_id: TargetID
    #: List of types: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/devtools_agent_host_impl.cc?ss=chromium&q=f:devtools%20-f:out%20%22::kTypeTab%5B%5D%22
    type: str
    title: str
    url: str
    #: Whether the target has an attached client.
    attached: bool
    #: Whether the target has access to the originating window. *(EXPERIMENTAL)*
    can_access_opener: bool
    #: *(Optional)* Id of the parent target, if any. For example, "iframe" target may have a "page" parent.
    parent_id: TargetID | None = None
    #: *(Optional)* Opener target Id
    opener_id: TargetID | None = None
    #: *(Optional)* Frame id of originating window (is only set if target has an opener). *(EXPERIMENTAL)*
    opener_frame_id: page.FrameId | None = None
    #: *(Optional)* Id of the parent frame, present for "iframe" and "worker" targets. For nested workers, this is the "ancestor" frame that created the first worker in the nested chain. *(EXPERIMENTAL)*
    parent_frame_id: page.FrameId | None = None
    #: *(Optional)* *(EXPERIMENTAL)*
    browser_context_id: browser.BrowserContextID | None = None
    #: *(Optional)* Provides additional details for specific target types. For example, for the type of "page", this may be set to "prerender". *(EXPERIMENTAL)*
    subtype: str | None = None
    #: *(Optional)* Embedder-specific target metadata. This is only set for targets of type "tab". *(EXPERIMENTAL)*
    embedder_data: T_JSON_DICT | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['targetId'] = self.target_id.to_json()
        json['type'] = self.type
        json['title'] = self.title
        json['url'] = self.url
        json['attached'] = self.attached
        json['canAccessOpener'] = self.can_access_opener
        if self.parent_id is not None:
            json['parentId'] = self.parent_id.to_json()
        if self.opener_id is not None:
            json['openerId'] = self.opener_id.to_json()
        if self.opener_frame_id is not None:
            json['openerFrameId'] = self.opener_frame_id.to_json()
        if self.parent_frame_id is not None:
            json['parentFrameId'] = self.parent_frame_id.to_json()
        if self.browser_context_id is not None:
            json['browserContextId'] = self.browser_context_id.to_json()
        if self.subtype is not None:
            json['subtype'] = self.subtype
        if self.embedder_data is not None:
            json['embedderData'] = self.embedder_data
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TargetInfo:
        return cls(
            target_id=TargetID.from_json(json['targetId']),
            type=json['type'],
            title=json['title'],
            url=json['url'],
            attached=json['attached'],
            can_access_opener=json['canAccessOpener'],
            parent_id=TargetID.from_json(json['parentId']) if json.get('parentId') is not None else None,
            opener_id=TargetID.from_json(json['openerId']) if json.get('openerId') is not None else None,
            opener_frame_id=page.FrameId.from_json(json['openerFrameId']) if json.get('openerFrameId') is not None else None,
            parent_frame_id=page.FrameId.from_json(json['parentFrameId']) if json.get('parentFrameId') is not None else None,
            browser_context_id=browser.BrowserContextID.from_json(json['browserContextId']) if json.get('browserContextId') is not None else None,
            subtype=json['subtype'] if json.get('subtype') is not None else None,
            embedder_data=json['embedderData'] if json.get('embedderData') is not None else None,
        )


@dataclass(slots=True)
class FilterEntry:
    '''A filter used by target query/discovery/auto-attach operations.

    **EXPERIMENTAL**
    '''
    #: *(Optional)* If set, causes exclusion of matching targets from the list.
    exclude: bool | None = None
    #: *(Optional)* If not present, matches any type.
    type: str | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        if self.exclude is not None:
            json['exclude'] = self.exclude
        if self.type is not None:
            json['type'] = self.type
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> FilterEntry:
        return cls(
            exclude=json['exclude'] if json.get('exclude') is not None else None,
            type=json['type'] if json.get('type') is not None else None,
        )


class TargetFilter(list):
    '''The entries in TargetFilter are matched sequentially against targets and
    the first entry that matches determines if the target is included or not,
    depending on the value of `exclude` field in the entry.
    If filter is not specified, the one assumed is
    [{type: "browser", exclude: true}, {type: "tab", exclude: true}, {}]
    (i.e. include everything but `browser` and `tab`).

    **EXPERIMENTAL**
    '''
    def to_json(self) -> list:
        return [i.to_json() for i in self]

    @classmethod
    def from_json(cls, json: list) -> TargetFilter:
        return cls([FilterEntry.from_json(i) for i in json])

    def __repr__(self) -> str:
        return f'TargetFilter({list.__repr__(self)})'


@dataclass(slots=True)
class RemoteLocation:
    '''**EXPERIMENTAL**'''
    host: str
    port: int

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['host'] = self.host
        json['port'] = self.port
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RemoteLocation:
        return cls(
            host=json['host'],
            port=json['port'],
        )


class WindowState(enum.StrEnum):
    '''The state of the target window.

    **EXPERIMENTAL**
    '''
    NORMAL = 'normal'
    MINIMIZED = 'minimized'
    MAXIMIZED = 'maximized'
    FULLSCREEN = 'fullscreen'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> WindowState:
        return cls(json)


def activate_target(target_id: TargetID) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Activates (focuses) the target.

    :param target_id:
    '''
    params: T_JSON_DICT = {}
    params['targetId'] = target_id.to_json()
    yield {'method': 'Target.activateTarget', 'params': params}


def attach_to_target(
        target_id: TargetID,
        flatten: bool | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SessionID]:
    '''Attaches to the target with given id.

    :param target_id:
    :param flatten: *(Optional)* Enables "flat" access to the session via specifying sessionId attribute in the commands. We plan to make this the default, deprecate non-flattened mode, and eventually retire it. See crbug.com/991325.
    :returns: Id assigned to the session.
    '''
    params: T_JSON_DICT = {}
    params['targetId'] = target_id.to_json()
    if flatten is not None:
        params['flatten'] = flatten
    json = yield {'method': 'Target.attachToTarget', 'params': params}
    return SessionID.from_json(json['sessionId'])


def attach_to_browser_target() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SessionID]:
    '''Attaches to the browser target, only uses flat sessionId mode.

    **EXPERIMENTAL**

    :returns: Id assigned to the session.
    '''
    json = yield {'method': 'Target.attachToBrowserTarget'}
    return SessionID.from_json(json['sessionId'])


def close_target(target_id: TargetID) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, bool]:
    '''Closes the target. If the target is a page that gets closed too.

    :param target_id:
    :returns: Always set to true. If an error occurs, the response indicates protocol error. *(DEPRECATED)*
    '''
    params: T_JSON_DICT = {}
    params['targetId'] = target_id.to_json()
    json = yield {'method': 'Target.closeTarget', 'params': params}
    return json['success']


def expose_dev_tools_protocol(
        target_id: TargetID,
        binding_name: str | None = None,
        inherit_permissions: bool | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Inject object to the target's main frame that provides a communication
    channel with browser target.

    Injected object will be available as `window[bindingName]`.

    The object has the following API:
    - `binding.send(json)` - a method to send messages over the remote debugging protocol
    - `binding.onmessage = json => handleMessage(json)` - a callback that will be called for the protocol notifications and command responses.

    **EXPERIMENTAL**

    :param target_id:
    :param binding_name: *(Optional)* Binding name, 'cdp' if not specified.
    :param inherit_permissions: *(Optional)* If true, inherits the current root session's permissions (default: false).
    '''
    params: T_JSON_DICT = {}
    params['targetId'] = target_id.to_json()
    if binding_name is not None:
        params['bindingName'] = binding_name
    if inherit_permissions is not None:
        params['inheritPermissions'] = inherit_permissions
    yield {'method': 'Target.exposeDevToolsProtocol', 'params': params}


def create_browser_context(
        dispose_on_detach: bool | None = None,
        proxy_server: str | None = None,
        proxy_bypass_list: str | None = None,
        origins_with_universal_network_access: list[str] | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, browser.BrowserContextID]:
    '''Creates a new empty BrowserContext. Similar to an incognito profile but you can have more than
    one.

    :param dispose_on_detach: *(Optional)* If specified, disposes this context when debugging session disconnects. *(EXPERIMENTAL)*
    :param proxy_server: *(Optional)* Proxy server, similar to the one passed to --proxy-server *(EXPERIMENTAL)*
    :param proxy_bypass_list: *(Optional)* Proxy bypass list, similar to the one passed to --proxy-bypass-list *(EXPERIMENTAL)*
    :param origins_with_universal_network_access: *(Optional)* An optional list of origins to grant unlimited cross-origin access to. Parts of the URL other than those constituting origin are ignored. *(EXPERIMENTAL)*
    :returns: The id of the context created.
    '''
    params: T_JSON_DICT = {}
    if dispose_on_detach is not None:
        params['disposeOnDetach'] = dispose_on_detach
    if proxy_server is not None:
        params['proxyServer'] = proxy_server
    if proxy_bypass_list is not None:
        params['proxyBypassList'] = proxy_bypass_list
    if origins_with_universal_network_access is not None:
        params['originsWithUniversalNetworkAccess'] = list(origins_with_universal_network_access)
    json = yield {'method': 'Target.createBrowserContext', 'params': params}
    return browser.BrowserContextID.from_json(json['browserContextId'])


def get_browser_contexts() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, tuple[list[browser.BrowserContextID], browser.BrowserContextID | None]]:
    '''Returns all browser contexts created with `Target.createBrowserContext` method.

    :returns: A tuple with the following items:
        0. **browserContextIds** — An array of browser context ids.
        1. **defaultBrowserContextId** — *(Optional)* The id of the default browser context if available. *(EXPERIMENTAL)*
    '''
    json = yield {'method': 'Target.getBrowserContexts'}
    return (
        [browser.BrowserContextID.from_json(i) for i in json['browserContextIds']],
        browser.BrowserContextID.from_json(json['defaultBrowserContextId']) if json.get('defaultBrowserContextId') is not None else None,
    )


def create_target(
        url: str,
        left: int | None = None,
        top: int | None = None,
        width: int | None = None,
        height: int | None = None,
        window_state: WindowState | None = None,
        browser_context_id: browser.BrowserContextID | None = None,
        enable_begin_frame_control: bool | None = None,
        new_window: bool | None = None,
        background: bool | None = None,
        for_tab: bool | None = None,
        hidden: bool | None = None,
        focus: bool | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, TargetID]:
    '''Creates a new page.

    :param url: The initial URL the page will be navigated to. An empty string indicates about:blank.
    :param left: *(Optional)* Frame left origin in DIP (requires newWindow to be true or headless shell). *(EXPERIMENTAL)*
    :param top: *(Optional)* Frame top origin in DIP (requires newWindow to be true or headless shell). *(EXPERIMENTAL)*
    :param width: *(Optional)* Frame width in DIP (requires newWindow to be true or headless shell).
    :param height: *(Optional)* Frame height in DIP (requires newWindow to be true or headless shell).
    :param window_state: *(Optional)* Frame window state (requires newWindow to be true or headless shell). Default is normal.
    :param browser_context_id: *(Optional)* The browser context to create the page in. *(EXPERIMENTAL)*
    :param enable_begin_frame_control: *(Optional)* Whether BeginFrames for this target will be controlled via DevTools (headless shell only, not supported on MacOS yet, false by default). *(EXPERIMENTAL)*
    :param new_window: *(Optional)* Whether to create a new Window or Tab (false by default, not supported by headless shell).
    :param background: *(Optional)* Whether to create the target in background or foreground (false by default, not supported by headless shell).
    :param for_tab: *(Optional)* Whether to create the target of type "tab". *(EXPERIMENTAL)*
    :param hidden: *(Optional)* Whether to create a hidden target. The hidden target is observable via protocol, but not present in the tab UI strip. Cannot be created with `forTab: true`, `newWindow: true` or `background: false`. The life-time of the tab is limited to the life-time of the session. *(EXPERIMENTAL)*
    :param focus: *(Optional)* If specified, determines whether the new target should be focused. By default, the focus behavior depends on the `background` parameter: - If `background` is false (default) and `focus` is omitted, the new target is focused and the browser window is brought to the foreground. - If `background` is false and `focus` is false, the target is opened but the browser window's focus remains unchanged (e.g., if the window was in the background, it stays there). - If `background` is true, setting `focus` to true is not supported and will result in an error. *(EXPERIMENTAL)*
    :returns: The id of the page opened.
    '''
    params: T_JSON_DICT = {}
    params['url'] = url
    if left is not None:
        params['left'] = left
    if top is not None:
        params['top'] = top
    if width is not None:
        params['width'] = width
    if height is not None:
        params['height'] = height
    if window_state is not None:
        params['windowState'] = window_state.to_json()
    if browser_context_id is not None:
        params['browserContextId'] = browser_context_id.to_json()
    if enable_begin_frame_control is not None:
        params['enableBeginFrameControl'] = enable_begin_frame_control
    if new_window is not None:
        params['newWindow'] = new_window
    if background is not None:
        params['background'] = background
    if for_tab is not None:
        params['forTab'] = for_tab
    if hidden is not None:
        params['hidden'] = hidden
    if focus is not None:
        params['focus'] = focus
    json = yield {'method': 'Target.createTarget', 'params': params}
    return TargetID.from_json(json['targetId'])


def detach_from_target(
        session_id: SessionID | None = None,
        target_id: TargetID | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Detaches session with given id.

    :param session_id: *(Optional)* Session to detach.
    :param target_id: *(Optional)* Deprecated. *(DEPRECATED)*
    '''
    params: T_JSON_DICT = {}
    if session_id is not None:
        params['sessionId'] = session_id.to_json()
    if target_id is not None:
        params['targetId'] = target_id.to_json()
    yield {'method': 'Target.detachFromTarget', 'params': params}


def dispose_browser_context(
        browser_context_id: browser.BrowserContextID,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Deletes a BrowserContext. All the belonging pages will be closed without calling their
    beforeunload hooks.

    :param browser_context_id:
    '''
    params: T_JSON_DICT = {}
    params['browserContextId'] = browser_context_id.to_json()
    yield {'method': 'Target.disposeBrowserContext', 'params': params}


def get_target_info(
        target_id: TargetID | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, TargetInfo]:
    '''Returns information about a target.

    **EXPERIMENTAL**

    :param target_id: *(Optional)*
    :returns:
    '''
    params: T_JSON_DICT = {}
    if target_id is not None:
        params['targetId'] = target_id.to_json()
    json = yield {'method': 'Target.getTargetInfo', 'params': params}
    return TargetInfo.from_json(json['targetInfo'])


def get_targets(
        filter: TargetFilter | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[TargetInfo]]:
    '''Retrieves a list of available targets.

    :param filter: *(Optional)* Only targets matching filter will be reported. If filter is not specified and target discovery is currently enabled, a filter used for target discovery is used for consistency. *(EXPERIMENTAL)*
    :returns: The list of targets.
    '''
    params: T_JSON_DICT = {}
    if filter is not None:
        params['filter'] = filter.to_json()
    json = yield {'method': 'Target.getTargets', 'params': params}
    return [TargetInfo.from_json(i) for i in json['targetInfos']]


def send_message_to_target(
        message: str,
        session_id: SessionID | None = None,
        target_id: TargetID | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Sends protocol message over session with given id.
    Consider using flat mode instead; see commands attachToTarget, setAutoAttach,
    and crbug.com/991325.

    **DEPRECATED**

    :param message:
    :param session_id: *(Optional)* Identifier of the session.
    :param target_id: *(Optional)* Deprecated. *(DEPRECATED)*
    '''
    params: T_JSON_DICT = {}
    params['message'] = message
    if session_id is not None:
        params['sessionId'] = session_id.to_json()
    if target_id is not None:
        params['targetId'] = target_id.to_json()
    yield {'method': 'Target.sendMessageToTarget', 'params': params}


def set_auto_attach(
        auto_attach: bool,
        wait_for_debugger_on_start: bool,
        flatten: bool | None = None,
        filter: TargetFilter | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Controls whether to automatically attach to new targets which are considered
    to be directly related to this one (for example, iframes or workers).
    When turned on, attaches to all existing related targets as well. When turned off,
    automatically detaches from all currently attached targets.
    This also clears all targets added by `autoAttachRelated` from the list of targets to watch
    for creation of related targets.
    You might want to call this recursively for auto-attached targets to attach
    to all available targets.

    :param auto_attach: Whether to auto-attach to related targets.
    :param wait_for_debugger_on_start: Whether to pause new targets when attaching to them. Use `Runtime.runIfWaitingForDebugger` to run paused targets.
    :param flatten: *(Optional)* Enables "flat" access to the session via specifying sessionId attribute in the commands. We plan to make this the default, deprecate non-flattened mode, and eventually retire it. See crbug.com/991325. *(EXPERIMENTAL)*
    :param filter: *(Optional)* Only targets matching filter will be attached. *(EXPERIMENTAL)*
    '''
    params: T_JSON_DICT = {}
    params['autoAttach'] = auto_attach
    params['waitForDebuggerOnStart'] = wait_for_debugger_on_start
    if flatten is not None:
        params['flatten'] = flatten
    if filter is not None:
        params['filter'] = filter.to_json()
    yield {'method': 'Target.setAutoAttach', 'params': params}


def auto_attach_related(
        target_id: TargetID,
        wait_for_debugger_on_start: bool,
        filter: TargetFilter | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Adds the specified target to the list of targets that will be monitored for any related target
    creation (such as child frames, child workers and new versions of service worker) and reported
    through `attachedToTarget`. The specified target is also auto-attached.
    This cancels the effect of any previous `setAutoAttach` and is also cancelled by subsequent
    `setAutoAttach`. Only available at the Browser target.

    **EXPERIMENTAL**

    :param target_id:
    :param wait_for_debugger_on_start: Whether to pause new targets when attaching to them. Use `Runtime.runIfWaitingForDebugger` to run paused targets.
    :param filter: *(Optional)* Only targets matching filter will be attached. *(EXPERIMENTAL)*
    '''
    params: T_JSON_DICT = {}
    params['targetId'] = target_id.to_json()
    params['waitForDebuggerOnStart'] = wait_for_debugger_on_start
    if filter is not None:
        params['filter'] = filter.to_json()
    yield {'method': 'Target.autoAttachRelated', 'params': params}


def set_discover_targets(
        discover: bool,
        filter: TargetFilter | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Controls whether to discover available targets and notify via
    `targetCreated/targetInfoChanged/targetDestroyed` events.

    :param discover: Whether to discover available targets.
    :param filter: *(Optional)* Only targets matching filter will be attached. If `discover` is false, `filter` must be omitted or empty. *(EXPERIMENTAL)*
    '''
    params: T_JSON_DICT = {}
    params['discover'] = discover
    if filter is not None:
        params['filter'] = filter.to_json()
    yield {'method': 'Target.setDiscoverTargets', 'params': params}


def set_remote_locations(
        locations: list[RemoteLocation],
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Enables target discovery for the specified locations, when `setDiscoverTargets` was set to
    `true`.

    **EXPERIMENTAL**

    :param locations: List of remote locations.
    '''
    params: T_JSON_DICT = {}
    params['locations'] = [i.to_json() for i in locations]
    yield {'method': 'Target.setRemoteLocations', 'params': params}


def get_dev_tools_target(
        target_id: TargetID,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, TargetID | None]:
    '''Gets the targetId of the DevTools page target opened for the given target
    (if any).

    **EXPERIMENTAL**

    :param target_id: Page or tab target ID.
    :returns: *(Optional)* The targetId of DevTools page target if exists.
    '''
    params: T_JSON_DICT = {}
    params['targetId'] = target_id.to_json()
    json = yield {'method': 'Target.getDevToolsTarget', 'params': params}
    return TargetID.from_json(json['targetId']) if json.get('targetId') is not None else None


def open_dev_tools(
        target_id: TargetID,
        panel_id: str | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, TargetID]:
    '''Opens a DevTools window for the target.

    **EXPERIMENTAL**

    :param target_id: This can be the page or tab target ID.
    :param panel_id: *(Optional)* The id of the panel we want DevTools to open initially. Currently supported panels are elements, console, network, sources, resources, timeline, chrome-recorder, heap-profiler, lighthouse, and security.
    :returns: The targetId of DevTools page target.
    '''
    params: T_JSON_DICT = {}
    params['targetId'] = target_id.to_json()
    if panel_id is not None:
        params['panelId'] = panel_id
    json = yield {'method': 'Target.openDevTools', 'params': params}
    return TargetID.from_json(json['targetId'])


@event_class('Target.attachedToTarget')
@dataclass(slots=True)
class AttachedToTarget:
    '''Issued when attached to target because of auto-attach or `attachToTarget` command.

    **EXPERIMENTAL**
    '''
    #: Identifier assigned to the session used to send/receive messages.
    session_id: SessionID
    target_info: TargetInfo
    waiting_for_debugger: bool

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AttachedToTarget:
        return cls(
            session_id=SessionID.from_json(json['sessionId']),
            target_info=TargetInfo.from_json(json['targetInfo']),
            waiting_for_debugger=json['waitingForDebugger'],
        )


@event_class('Target.detachedFromTarget')
@dataclass(slots=True)
class DetachedFromTarget:
    '''Issued when detached from target for any reason (including `detachFromTarget` command). Can be
    issued multiple times per target if multiple sessions have been attached to it.

    **EXPERIMENTAL**
    '''
    #: Detached session identifier.
    session_id: SessionID
    #: *(Optional)* Deprecated. *(DEPRECATED)*
    target_id: TargetID | None = None

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DetachedFromTarget:
        return cls(
            session_id=SessionID.from_json(json['sessionId']),
            target_id=TargetID.from_json(json['targetId']) if json.get('targetId') is not None else None,
        )


@event_class('Target.receivedMessageFromTarget')
@dataclass(slots=True)
class ReceivedMessageFromTarget:
    '''Notifies about a new protocol message received from the session (as reported in
    `attachedToTarget` event).
    '''
    #: Identifier of a session which sends a message.
    session_id: SessionID
    message: str
    #: *(Optional)* Deprecated. *(DEPRECATED)*
    target_id: TargetID | None = None

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ReceivedMessageFromTarget:
        return cls(
            session_id=SessionID.from_json(json['sessionId']),
            message=json['message'],
            target_id=TargetID.from_json(json['targetId']) if json.get('targetId') is not None else None,
        )


@event_class('Target.targetCreated')
@dataclass(slots=True)
class TargetCreated:
    '''Issued when a possible inspection target is created.'''
    target_info: TargetInfo

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TargetCreated:
        return cls(
            target_info=TargetInfo.from_json(json['targetInfo']),
        )


@event_class('Target.targetDestroyed')
@dataclass(slots=True)
class TargetDestroyed:
    '''Issued when a target is destroyed.'''
    target_id: TargetID

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TargetDestroyed:
        return cls(
            target_id=TargetID.from_json(json['targetId']),
        )


@event_class('Target.targetCrashed')
@dataclass(slots=True)
class TargetCrashed:
    '''Issued when a target has crashed.'''
    target_id: TargetID
    #: Termination status type.
    status: str
    #: Termination error code.
    error_code: int

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TargetCrashed:
        return cls(
            target_id=TargetID.from_json(json['targetId']),
            status=json['status'],
            error_code=json['errorCode'],
        )


@event_class('Target.targetInfoChanged')
@dataclass(slots=True)
class TargetInfoChanged:
    '''Issued when some information about a target has changed. This only happens between
    `targetCreated` and `targetDestroyed`.
    '''
    target_info: TargetInfo

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TargetInfoChanged:
        return cls(
            target_info=TargetInfo.from_json(json['targetInfo']),
        )
