# DO NOT EDIT — generated by purecdp._generator from Tracing (devtools-protocol 3bd8f01934b5)
'''CDP domain: Tracing.'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class

from . import io


class MemoryDumpConfig(dict):
    '''Configuration for memory dump. Used only when "memory-infra" category is enabled.

    **EXPERIMENTAL**
    '''
    def to_json(self) -> T_JSON_DICT:
        return dict(self)

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> MemoryDumpConfig:
        return cls(json)

    def __repr__(self) -> str:
        return f'MemoryDumpConfig({dict.__repr__(self)})'


@dataclass(slots=True)
class TraceConfig:
    #: *(Optional)* Controls how the trace buffer stores data. The default is `recordUntilFull`. Allowed values: recordUntilFull, recordContinuously, recordAsMuchAsPossible, echoToConsole *(EXPERIMENTAL)*
    record_mode: str | None = None
    #: *(Optional)* Size of the trace buffer in kilobytes. If not specified or zero is passed, a default value of 200 MB would be used. *(EXPERIMENTAL)*
    trace_buffer_size_in_kb: float | None = None
    #: *(Optional)* Turns on JavaScript stack sampling. *(EXPERIMENTAL)*
    enable_sampling: bool | None = None
    #: *(Optional)* Turns on system tracing. *(EXPERIMENTAL)*
    enable_systrace: bool | None = None
    #: *(Optional)* Turns on argument filter. *(EXPERIMENTAL)*
    enable_argument_filter: bool | None = None
    #: *(Optional)* Included category filters.
    included_categories: list[str] | None = None
    #: *(Optional)* Excluded category filters.
    excluded_categories: list[str] | None = None
    #: *(Optional)* Configuration to synthesize the delays in tracing. *(EXPERIMENTAL)*
    synthetic_delays: list[str] | None = None
    #: *(Optional)* Configuration for memory dump triggers. Used only when "memory-infra" category is enabled. *(EXPERIMENTAL)*
    memory_dump_config: MemoryDumpConfig | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        if self.record_mode is not None:
            json['recordMode'] = self.record_mode
        if self.trace_buffer_size_in_kb is not None:
            json['traceBufferSizeInKb'] = self.trace_buffer_size_in_kb
        if self.enable_sampling is not None:
            json['enableSampling'] = self.enable_sampling
        if self.enable_systrace is not None:
            json['enableSystrace'] = self.enable_systrace
        if self.enable_argument_filter is not None:
            json['enableArgumentFilter'] = self.enable_argument_filter
        if self.included_categories is not None:
            json['includedCategories'] = list(self.included_categories)
        if self.excluded_categories is not None:
            json['excludedCategories'] = list(self.excluded_categories)
        if self.synthetic_delays is not None:
            json['syntheticDelays'] = list(self.synthetic_delays)
        if self.memory_dump_config is not None:
            json['memoryDumpConfig'] = self.memory_dump_config.to_json()
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TraceConfig:
        return cls(
            record_mode=json['recordMode'] if json.get('recordMode') is not None else None,
            trace_buffer_size_in_kb=float(json['traceBufferSizeInKb']) if json.get('traceBufferSizeInKb') is not None else None,
            enable_sampling=json['enableSampling'] if json.get('enableSampling') is not None else None,
            enable_systrace=json['enableSystrace'] if json.get('enableSystrace') is not None else None,
            enable_argument_filter=json['enableArgumentFilter'] if json.get('enableArgumentFilter') is not None else None,
            included_categories=list(json['includedCategories']) if json.get('includedCategories') is not None else None,
            excluded_categories=list(json['excludedCategories']) if json.get('excludedCategories') is not None else None,
            synthetic_delays=list(json['syntheticDelays']) if json.get('syntheticDelays') is not None else None,
            memory_dump_config=MemoryDumpConfig.from_json(json['memoryDumpConfig']) if json.get('memoryDumpConfig') is not None else None,
        )


class StreamFormat(enum.StrEnum):
    '''Data format of a trace. Can be either the legacy JSON format or the
    protocol buffer format. Note that the JSON format will be deprecated soon.

    **EXPERIMENTAL**
    '''
    JSON = 'json'
    PROTO = 'proto'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> StreamFormat:
        return cls(json)


class StreamCompression(enum.StrEnum):
    '''Compression type to use for traces returned via streams.

    **EXPERIMENTAL**
    '''
    NONE = 'none'
    GZIP = 'gzip'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> StreamCompression:
        return cls(json)


class MemoryDumpLevelOfDetail(enum.StrEnum):
    '''Details exposed when memory request explicitly declared.
    Keep consistent with memory_dump_request_args.h and
    memory_instrumentation.mojom

    **EXPERIMENTAL**
    '''
    BACKGROUND = 'background'
    LIGHT = 'light'
    DETAILED = 'detailed'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> MemoryDumpLevelOfDetail:
        return cls(json)


class TracingBackend(enum.StrEnum):
    '''Backend type to use for tracing. `chrome` uses the Chrome-integrated
    tracing service and is supported on all platforms. `system` is only
    supported on Chrome OS and uses the Perfetto system tracing service.
    `auto` chooses `system` when the perfettoConfig provided to Tracing.start
    specifies at least one non-Chrome data source; otherwise uses `chrome`.

    **EXPERIMENTAL**
    '''
    AUTO = 'auto'
    CHROME = 'chrome'
    SYSTEM = 'system'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> TracingBackend:
        return cls(json)


def end() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Stop trace events collection.'''
    yield {'method': 'Tracing.end'}


def get_categories() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[str]]:
    '''Gets supported tracing categories.

    **EXPERIMENTAL**

    :returns: A list of supported tracing categories.
    '''
    json = yield {'method': 'Tracing.getCategories'}
    return list(json['categories'])


def get_track_event_descriptor() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, str]:
    '''Return a descriptor for all available tracing categories.

    **EXPERIMENTAL**

    :returns: Base64-encoded serialized perfetto.protos.TrackEventDescriptor protobuf message. (Encoded as a base64 string when passed over JSON)
    '''
    json = yield {'method': 'Tracing.getTrackEventDescriptor'}
    return json['descriptor']


def record_clock_sync_marker(sync_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Record a clock sync marker in the trace.

    **EXPERIMENTAL**

    :param sync_id: The ID of this clock sync marker
    '''
    params: T_JSON_DICT = {}
    params['syncId'] = sync_id
    yield {'method': 'Tracing.recordClockSyncMarker', 'params': params}


def request_memory_dump(
        deterministic: bool | None = None,
        level_of_detail: MemoryDumpLevelOfDetail | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, tuple[str, bool]]:
    '''Request a global memory dump.

    **EXPERIMENTAL**

    :param deterministic: *(Optional)* Enables more deterministic results by forcing garbage collection
    :param level_of_detail: *(Optional)* Specifies level of details in memory dump. Defaults to "detailed".
    :returns: A tuple with the following items:
        0. **dumpGuid** — GUID of the resulting global memory dump.
        1. **success** — True iff the global memory dump succeeded.
    '''
    params: T_JSON_DICT = {}
    if deterministic is not None:
        params['deterministic'] = deterministic
    if level_of_detail is not None:
        params['levelOfDetail'] = level_of_detail.to_json()
    json = yield {'method': 'Tracing.requestMemoryDump', 'params': params}
    return (
        json['dumpGuid'],
        json['success'],
    )


def start(
        categories: str | None = None,
        options: str | None = None,
        buffer_usage_reporting_interval: float | None = None,
        transfer_mode: str | None = None,
        stream_format: StreamFormat | None = None,
        stream_compression: StreamCompression | None = None,
        trace_config: TraceConfig | None = None,
        perfetto_config: str | None = None,
        tracing_backend: TracingBackend | None = None,
        screenshot_max_size: int | None = None,
        screenshot_max_count: int | None = None,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Start trace events collection.

    :param categories: *(Optional)* Category/tag filter *(EXPERIMENTAL)* *(DEPRECATED)*
    :param options: *(Optional)* Tracing options *(EXPERIMENTAL)* *(DEPRECATED)*
    :param buffer_usage_reporting_interval: *(Optional)* If set, the agent will issue bufferUsage events at this interval, specified in milliseconds *(EXPERIMENTAL)*
    :param transfer_mode: *(Optional)* Whether to report trace events as series of dataCollected events or to save trace to a stream (defaults to `ReportEvents`). Allowed values: ReportEvents, ReturnAsStream
    :param stream_format: *(Optional)* Trace data format to use. This only applies when using `ReturnAsStream` transfer mode (defaults to `json`).
    :param stream_compression: *(Optional)* Compression format to use. This only applies when using `ReturnAsStream` transfer mode (defaults to `none`) *(EXPERIMENTAL)*
    :param trace_config: *(Optional)*
    :param perfetto_config: *(Optional)* Base64-encoded serialized perfetto.protos.TraceConfig protobuf message When specified, the parameters `categories`, `options`, `traceConfig` are ignored. (Encoded as a base64 string when passed over JSON) *(EXPERIMENTAL)*
    :param tracing_backend: *(Optional)* Backend type (defaults to `auto`) *(EXPERIMENTAL)*
    :param screenshot_max_size: *(Optional)* Maximum width and height (in pixels) of each captured screenshot. Only used when the `disabled-by-default-devtools.screenshot` category is enabled. Defaults to 500. The combined memory footprint of screenshots (`screenshotMaxSize` * `screenshotMaxSize` * 4 * `screenshotMaxCount`) is clamped to the existing per-session budget. *(EXPERIMENTAL)*
    :param screenshot_max_count: *(Optional)* Maximum number of screenshots captured during a single tracing session. Only used when the `disabled-by-default-devtools.screenshot` category is enabled. Defaults to 450. Clamped together with `screenshotMaxSize` to stay within the per-session screenshot memory budget. *(EXPERIMENTAL)*
    '''
    params: T_JSON_DICT = {}
    if categories is not None:
        params['categories'] = categories
    if options is not None:
        params['options'] = options
    if buffer_usage_reporting_interval is not None:
        params['bufferUsageReportingInterval'] = buffer_usage_reporting_interval
    if transfer_mode is not None:
        params['transferMode'] = transfer_mode
    if stream_format is not None:
        params['streamFormat'] = stream_format.to_json()
    if stream_compression is not None:
        params['streamCompression'] = stream_compression.to_json()
    if trace_config is not None:
        params['traceConfig'] = trace_config.to_json()
    if perfetto_config is not None:
        params['perfettoConfig'] = perfetto_config
    if tracing_backend is not None:
        params['tracingBackend'] = tracing_backend.to_json()
    if screenshot_max_size is not None:
        params['screenshotMaxSize'] = screenshot_max_size
    if screenshot_max_count is not None:
        params['screenshotMaxCount'] = screenshot_max_count
    yield {'method': 'Tracing.start', 'params': params}


@event_class('Tracing.bufferUsage')
@dataclass(slots=True)
class BufferUsage:
    '''**EXPERIMENTAL**'''
    #: *(Optional)* A number in range [0..1] that indicates the used size of event buffer as a fraction of its total size.
    percent_full: float | None = None
    #: *(Optional)* An approximate number of events in the trace log.
    event_count: float | None = None
    #: *(Optional)* A number in range [0..1] that indicates the used size of event buffer as a fraction of its total size.
    value: float | None = None

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> BufferUsage:
        return cls(
            percent_full=float(json['percentFull']) if json.get('percentFull') is not None else None,
            event_count=float(json['eventCount']) if json.get('eventCount') is not None else None,
            value=float(json['value']) if json.get('value') is not None else None,
        )


@event_class('Tracing.dataCollected')
@dataclass(slots=True)
class DataCollected:
    '''Contains a bucket of collected trace events. When tracing is stopped collected events will be
    sent as a sequence of dataCollected events followed by tracingComplete event.

    **EXPERIMENTAL**
    '''
    value: list[T_JSON_DICT]

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DataCollected:
        return cls(
            value=list(json['value']),
        )


@event_class('Tracing.tracingComplete')
@dataclass(slots=True)
class TracingComplete:
    '''Signals that tracing is stopped and there is no trace buffers pending flush, all data were
    delivered via dataCollected events.
    '''
    #: Indicates whether some trace data is known to have been lost, e.g. because the trace ring buffer wrapped around.
    data_loss_occurred: bool
    #: *(Optional)* A handle of the stream that holds resulting trace data.
    stream: io.StreamHandle | None = None
    #: *(Optional)* Trace data format of returned stream.
    trace_format: StreamFormat | None = None
    #: *(Optional)* Compression format of returned stream.
    stream_compression: StreamCompression | None = None

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TracingComplete:
        return cls(
            data_loss_occurred=json['dataLossOccurred'],
            stream=io.StreamHandle.from_json(json['stream']) if json.get('stream') is not None else None,
            trace_format=StreamFormat.from_json(json['traceFormat']) if json.get('traceFormat') is not None else None,
            stream_compression=StreamCompression.from_json(json['streamCompression']) if json.get('streamCompression') is not None else None,
        )
