# DO NOT EDIT — generated by purecdp._generator from WebMCP (devtools-protocol 3bd8f01934b5)
'''CDP domain: WebMCP.

**EXPERIMENTAL**
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class

from . import dom, page, runtime


@dataclass(slots=True)
class Annotation:
    '''Tool annotations'''
    #: *(Optional)* A hint indicating that the tool does not modify any state.
    read_only: bool | None = None
    #: *(Optional)* A hint indicating that the tool output may contain untrusted content, ex: UGC, 3rd party data.
    untrusted_content: bool | None = None
    #: *(Optional)* If the declarative tool was declared with the autosubmit attribute.
    autosubmit: bool | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        if self.read_only is not None:
            json['readOnly'] = self.read_only
        if self.untrusted_content is not None:
            json['untrustedContent'] = self.untrusted_content
        if self.autosubmit is not None:
            json['autosubmit'] = self.autosubmit
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Annotation:
        return cls(
            read_only=json['readOnly'] if json.get('readOnly') is not None else None,
            untrusted_content=json['untrustedContent'] if json.get('untrustedContent') is not None else None,
            autosubmit=json['autosubmit'] if json.get('autosubmit') is not None else None,
        )


class InvocationStatus(enum.StrEnum):
    '''Represents the status of a tool invocation.'''
    COMPLETED = 'Completed'
    CANCELED = 'Canceled'
    ERROR = 'Error'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> InvocationStatus:
        return cls(json)


@dataclass(slots=True)
class Tool:
    '''Definition of a tool that can be invoked.'''
    #: Tool name.
    name: str
    #: Tool description.
    description: str
    #: Frame identifier associated with the tool registration.
    frame_id: page.FrameId
    #: *(Optional)* Schema for the tool's input parameters.
    input_schema: T_JSON_DICT | None = None
    #: *(Optional)* Optional annotations for the tool.
    annotations: Annotation | None = None
    #: *(Optional)* Optional node ID for declarative tools.
    backend_node_id: dom.BackendNodeId | None = None
    #: *(Optional)* The stack trace at the time of the registration.
    stack_trace: runtime.StackTrace | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['name'] = self.name
        json['description'] = self.description
        json['frameId'] = self.frame_id.to_json()
        if self.input_schema is not None:
            json['inputSchema'] = self.input_schema
        if self.annotations is not None:
            json['annotations'] = self.annotations.to_json()
        if self.backend_node_id is not None:
            json['backendNodeId'] = self.backend_node_id.to_json()
        if self.stack_trace is not None:
            json['stackTrace'] = self.stack_trace.to_json()
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Tool:
        return cls(
            name=json['name'],
            description=json['description'],
            frame_id=page.FrameId.from_json(json['frameId']),
            input_schema=json['inputSchema'] if json.get('inputSchema') is not None else None,
            annotations=Annotation.from_json(json['annotations']) if json.get('annotations') is not None else None,
            backend_node_id=dom.BackendNodeId.from_json(json['backendNodeId']) if json.get('backendNodeId') is not None else None,
            stack_trace=runtime.StackTrace.from_json(json['stackTrace']) if json.get('stackTrace') is not None else None,
        )


@dataclass(slots=True)
class RemovedTool:
    '''Definition of a tool that was removed.'''
    #: Tool name.
    name: str
    #: Frame identifier associated with the tool registration.
    frame_id: page.FrameId

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['name'] = self.name
        json['frameId'] = self.frame_id.to_json()
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RemovedTool:
        return cls(
            name=json['name'],
            frame_id=page.FrameId.from_json(json['frameId']),
        )


def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Enables the WebMCP domain, allowing events to be sent. Enabling the domain will trigger a toolsAdded event for
    all currently registered tools.
    '''
    yield {'method': 'WebMCP.enable'}


def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Disables the WebMCP domain.'''
    yield {'method': 'WebMCP.disable'}


def invoke_tool(
        frame_id: page.FrameId,
        tool_name: str,
        input: T_JSON_DICT,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, str]:
    '''Invokes a registered tool.

    :param frame_id: Frame in which to invoke the tool.
    :param tool_name: Name of the tool to invoke.
    :param input: Input parameters for the tool, matching the tool's inputSchema.
    :returns: Unique identifier for this invocation. Response is sent before tool events.
    '''
    params: T_JSON_DICT = {}
    params['frameId'] = frame_id.to_json()
    params['toolName'] = tool_name
    params['input'] = input
    json = yield {'method': 'WebMCP.invokeTool', 'params': params}
    return json['invocationId']


def cancel_invocation(invocation_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Cancels a pending tool invocation.

    :param invocation_id: Invocation identifier to cancel.
    '''
    params: T_JSON_DICT = {}
    params['invocationId'] = invocation_id
    yield {'method': 'WebMCP.cancelInvocation', 'params': params}


@event_class('WebMCP.toolsAdded')
@dataclass(slots=True)
class ToolsAdded:
    '''Event fired when new tools are added.'''
    #: Array of tools that were added.
    tools: list[Tool]

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ToolsAdded:
        return cls(
            tools=[Tool.from_json(i) for i in json['tools']],
        )


@event_class('WebMCP.toolsRemoved')
@dataclass(slots=True)
class ToolsRemoved:
    '''Event fired when tools are removed.'''
    #: Array of tools that were removed.
    tools: list[RemovedTool]

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ToolsRemoved:
        return cls(
            tools=[RemovedTool.from_json(i) for i in json['tools']],
        )


@event_class('WebMCP.toolInvoked')
@dataclass(slots=True)
class ToolInvoked:
    '''Event fired when a tool invocation starts.'''
    #: Name of the tool to invoke.
    tool_name: str
    #: Frame id
    frame_id: page.FrameId
    #: Invocation identifier.
    invocation_id: str
    #: The input parameters used for the invocation.
    input: str

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ToolInvoked:
        return cls(
            tool_name=json['toolName'],
            frame_id=page.FrameId.from_json(json['frameId']),
            invocation_id=json['invocationId'],
            input=json['input'],
        )


@event_class('WebMCP.toolResponded')
@dataclass(slots=True)
class ToolResponded:
    '''Event fired when a tool invocation completes or fails.'''
    #: Invocation identifier.
    invocation_id: str
    #: Status of the invocation.
    status: InvocationStatus
    #: *(Optional)* Output or error delivered as delivered to the agent. Missing if `status` is anything other than Completed. Note: The output is untrusted and poses a prompt injection risk. Clients should treat this as potentially malicious user input.
    output: typing.Any | None = None
    #: *(Optional)* Error text for protocol users.
    error_text: str | None = None
    #: *(Optional)* The exception object, if the javascript tool threw an error>
    exception: runtime.RemoteObject | None = None

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ToolResponded:
        return cls(
            invocation_id=json['invocationId'],
            status=InvocationStatus.from_json(json['status']),
            output=json['output'] if json.get('output') is not None else None,
            error_text=json['errorText'] if json.get('errorText') is not None else None,
            exception=runtime.RemoteObject.from_json(json['exception']) if json.get('exception') is not None else None,
        )
