# DO NOT EDIT — generated by purecdp._generator from WebAudio (devtools-protocol 3bd8f01934b5)
'''CDP domain: WebAudio.

This domain allows inspection of Web Audio API.
https://webaudio.github.io/web-audio-api/

**EXPERIMENTAL**
'''

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass

from .._shared import T_JSON_DICT, event_class


class GraphObjectId(str):
    '''An unique ID for a graph object (AudioContext, AudioNode, AudioParam) in Web Audio API'''
    def to_json(self) -> str:
        return str(self)

    @classmethod
    def from_json(cls, json: str) -> GraphObjectId:
        return cls(json)

    def __repr__(self) -> str:
        return f'GraphObjectId({str.__repr__(self)})'


class ContextType(enum.StrEnum):
    '''Enum of BaseAudioContext types'''
    REALTIME = 'realtime'
    OFFLINE = 'offline'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> ContextType:
        return cls(json)


class ContextState(enum.StrEnum):
    '''Enum of AudioContextState from the spec'''
    SUSPENDED = 'suspended'
    RUNNING = 'running'
    CLOSED = 'closed'
    INTERRUPTED = 'interrupted'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> ContextState:
        return cls(json)


class NodeType(str):
    '''Enum of AudioNode types'''
    def to_json(self) -> str:
        return str(self)

    @classmethod
    def from_json(cls, json: str) -> NodeType:
        return cls(json)

    def __repr__(self) -> str:
        return f'NodeType({str.__repr__(self)})'


class ChannelCountMode(enum.StrEnum):
    '''Enum of AudioNode::ChannelCountMode from the spec'''
    CLAMPED_MAX = 'clamped-max'
    EXPLICIT = 'explicit'
    MAX = 'max'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> ChannelCountMode:
        return cls(json)


class ChannelInterpretation(enum.StrEnum):
    '''Enum of AudioNode::ChannelInterpretation from the spec'''
    DISCRETE = 'discrete'
    SPEAKERS = 'speakers'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> ChannelInterpretation:
        return cls(json)


class ParamType(str):
    '''Enum of AudioParam types'''
    def to_json(self) -> str:
        return str(self)

    @classmethod
    def from_json(cls, json: str) -> ParamType:
        return cls(json)

    def __repr__(self) -> str:
        return f'ParamType({str.__repr__(self)})'


class AutomationRate(enum.StrEnum):
    '''Enum of AudioParam::AutomationRate from the spec'''
    A_RATE = 'a-rate'
    K_RATE = 'k-rate'

    def to_json(self) -> str:
        return self.value

    @classmethod
    def from_json(cls, json: str) -> AutomationRate:
        return cls(json)


@dataclass(slots=True)
class ContextRealtimeData:
    '''Fields in AudioContext that change in real-time.'''
    #: The current context time in second in BaseAudioContext.
    current_time: float
    #: The time spent on rendering graph divided by render quantum duration, and multiplied by 100. 100 means the audio renderer reached the full capacity and glitch may occur.
    render_capacity: float
    #: A running mean of callback interval.
    callback_interval_mean: float
    #: A running variance of callback interval.
    callback_interval_variance: float

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['currentTime'] = self.current_time
        json['renderCapacity'] = self.render_capacity
        json['callbackIntervalMean'] = self.callback_interval_mean
        json['callbackIntervalVariance'] = self.callback_interval_variance
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ContextRealtimeData:
        return cls(
            current_time=float(json['currentTime']),
            render_capacity=float(json['renderCapacity']),
            callback_interval_mean=float(json['callbackIntervalMean']),
            callback_interval_variance=float(json['callbackIntervalVariance']),
        )


@dataclass(slots=True)
class BaseAudioContext:
    '''Protocol object for BaseAudioContext'''
    context_id: GraphObjectId
    context_type: ContextType
    context_state: ContextState
    #: Platform-dependent callback buffer size.
    callback_buffer_size: float
    #: Number of output channels supported by audio hardware in use.
    max_output_channel_count: float
    #: Context sample rate.
    sample_rate: float
    #: *(Optional)*
    realtime_data: ContextRealtimeData | None = None

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['contextId'] = self.context_id.to_json()
        json['contextType'] = self.context_type.to_json()
        json['contextState'] = self.context_state.to_json()
        json['callbackBufferSize'] = self.callback_buffer_size
        json['maxOutputChannelCount'] = self.max_output_channel_count
        json['sampleRate'] = self.sample_rate
        if self.realtime_data is not None:
            json['realtimeData'] = self.realtime_data.to_json()
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> BaseAudioContext:
        return cls(
            context_id=GraphObjectId.from_json(json['contextId']),
            context_type=ContextType.from_json(json['contextType']),
            context_state=ContextState.from_json(json['contextState']),
            callback_buffer_size=float(json['callbackBufferSize']),
            max_output_channel_count=float(json['maxOutputChannelCount']),
            sample_rate=float(json['sampleRate']),
            realtime_data=ContextRealtimeData.from_json(json['realtimeData']) if json.get('realtimeData') is not None else None,
        )


@dataclass(slots=True)
class AudioListener:
    '''Protocol object for AudioListener'''
    listener_id: GraphObjectId
    context_id: GraphObjectId

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['listenerId'] = self.listener_id.to_json()
        json['contextId'] = self.context_id.to_json()
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioListener:
        return cls(
            listener_id=GraphObjectId.from_json(json['listenerId']),
            context_id=GraphObjectId.from_json(json['contextId']),
        )


@dataclass(slots=True)
class AudioNode:
    '''Protocol object for AudioNode'''
    node_id: GraphObjectId
    context_id: GraphObjectId
    node_type: NodeType
    number_of_inputs: float
    number_of_outputs: float
    channel_count: float
    channel_count_mode: ChannelCountMode
    channel_interpretation: ChannelInterpretation

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['nodeId'] = self.node_id.to_json()
        json['contextId'] = self.context_id.to_json()
        json['nodeType'] = self.node_type.to_json()
        json['numberOfInputs'] = self.number_of_inputs
        json['numberOfOutputs'] = self.number_of_outputs
        json['channelCount'] = self.channel_count
        json['channelCountMode'] = self.channel_count_mode.to_json()
        json['channelInterpretation'] = self.channel_interpretation.to_json()
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioNode:
        return cls(
            node_id=GraphObjectId.from_json(json['nodeId']),
            context_id=GraphObjectId.from_json(json['contextId']),
            node_type=NodeType.from_json(json['nodeType']),
            number_of_inputs=float(json['numberOfInputs']),
            number_of_outputs=float(json['numberOfOutputs']),
            channel_count=float(json['channelCount']),
            channel_count_mode=ChannelCountMode.from_json(json['channelCountMode']),
            channel_interpretation=ChannelInterpretation.from_json(json['channelInterpretation']),
        )


@dataclass(slots=True)
class AudioParam:
    '''Protocol object for AudioParam'''
    param_id: GraphObjectId
    node_id: GraphObjectId
    context_id: GraphObjectId
    param_type: ParamType
    rate: AutomationRate
    default_value: float
    min_value: float
    max_value: float

    def to_json(self) -> T_JSON_DICT:
        json: T_JSON_DICT = {}
        json['paramId'] = self.param_id.to_json()
        json['nodeId'] = self.node_id.to_json()
        json['contextId'] = self.context_id.to_json()
        json['paramType'] = self.param_type.to_json()
        json['rate'] = self.rate.to_json()
        json['defaultValue'] = self.default_value
        json['minValue'] = self.min_value
        json['maxValue'] = self.max_value
        return json

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioParam:
        return cls(
            param_id=GraphObjectId.from_json(json['paramId']),
            node_id=GraphObjectId.from_json(json['nodeId']),
            context_id=GraphObjectId.from_json(json['contextId']),
            param_type=ParamType.from_json(json['paramType']),
            rate=AutomationRate.from_json(json['rate']),
            default_value=float(json['defaultValue']),
            min_value=float(json['minValue']),
            max_value=float(json['maxValue']),
        )


def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Enables the WebAudio domain and starts sending context lifetime events.'''
    yield {'method': 'WebAudio.enable'}


def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''Disables the WebAudio domain.'''
    yield {'method': 'WebAudio.disable'}


def get_realtime_data(
        context_id: GraphObjectId,
) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, ContextRealtimeData]:
    '''Fetch the realtime data from the registered contexts.

    :param context_id:
    :returns:
    '''
    params: T_JSON_DICT = {}
    params['contextId'] = context_id.to_json()
    json = yield {'method': 'WebAudio.getRealtimeData', 'params': params}
    return ContextRealtimeData.from_json(json['realtimeData'])


@event_class('WebAudio.contextCreated')
@dataclass(slots=True)
class ContextCreated:
    '''Notifies that a new BaseAudioContext has been created.'''
    context: BaseAudioContext

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ContextCreated:
        return cls(
            context=BaseAudioContext.from_json(json['context']),
        )


@event_class('WebAudio.contextWillBeDestroyed')
@dataclass(slots=True)
class ContextWillBeDestroyed:
    '''Notifies that an existing BaseAudioContext will be destroyed.'''
    context_id: GraphObjectId

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ContextWillBeDestroyed:
        return cls(
            context_id=GraphObjectId.from_json(json['contextId']),
        )


@event_class('WebAudio.contextChanged')
@dataclass(slots=True)
class ContextChanged:
    '''Notifies that existing BaseAudioContext has changed some properties (id stays the same)..'''
    context: BaseAudioContext

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ContextChanged:
        return cls(
            context=BaseAudioContext.from_json(json['context']),
        )


@event_class('WebAudio.audioListenerCreated')
@dataclass(slots=True)
class AudioListenerCreated:
    '''Notifies that the construction of an AudioListener has finished.'''
    listener: AudioListener

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioListenerCreated:
        return cls(
            listener=AudioListener.from_json(json['listener']),
        )


@event_class('WebAudio.audioListenerWillBeDestroyed')
@dataclass(slots=True)
class AudioListenerWillBeDestroyed:
    '''Notifies that a new AudioListener has been created.'''
    context_id: GraphObjectId
    listener_id: GraphObjectId

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioListenerWillBeDestroyed:
        return cls(
            context_id=GraphObjectId.from_json(json['contextId']),
            listener_id=GraphObjectId.from_json(json['listenerId']),
        )


@event_class('WebAudio.audioNodeCreated')
@dataclass(slots=True)
class AudioNodeCreated:
    '''Notifies that a new AudioNode has been created.'''
    node: AudioNode

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioNodeCreated:
        return cls(
            node=AudioNode.from_json(json['node']),
        )


@event_class('WebAudio.audioNodeWillBeDestroyed')
@dataclass(slots=True)
class AudioNodeWillBeDestroyed:
    '''Notifies that an existing AudioNode has been destroyed.'''
    context_id: GraphObjectId
    node_id: GraphObjectId

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioNodeWillBeDestroyed:
        return cls(
            context_id=GraphObjectId.from_json(json['contextId']),
            node_id=GraphObjectId.from_json(json['nodeId']),
        )


@event_class('WebAudio.audioParamCreated')
@dataclass(slots=True)
class AudioParamCreated:
    '''Notifies that a new AudioParam has been created.'''
    param: AudioParam

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioParamCreated:
        return cls(
            param=AudioParam.from_json(json['param']),
        )


@event_class('WebAudio.audioParamWillBeDestroyed')
@dataclass(slots=True)
class AudioParamWillBeDestroyed:
    '''Notifies that an existing AudioParam has been destroyed.'''
    context_id: GraphObjectId
    node_id: GraphObjectId
    param_id: GraphObjectId

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioParamWillBeDestroyed:
        return cls(
            context_id=GraphObjectId.from_json(json['contextId']),
            node_id=GraphObjectId.from_json(json['nodeId']),
            param_id=GraphObjectId.from_json(json['paramId']),
        )


@event_class('WebAudio.nodesConnected')
@dataclass(slots=True)
class NodesConnected:
    '''Notifies that two AudioNodes are connected.'''
    context_id: GraphObjectId
    source_id: GraphObjectId
    destination_id: GraphObjectId
    #: *(Optional)*
    source_output_index: float | None = None
    #: *(Optional)*
    destination_input_index: float | None = None

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> NodesConnected:
        return cls(
            context_id=GraphObjectId.from_json(json['contextId']),
            source_id=GraphObjectId.from_json(json['sourceId']),
            destination_id=GraphObjectId.from_json(json['destinationId']),
            source_output_index=float(json['sourceOutputIndex']) if json.get('sourceOutputIndex') is not None else None,
            destination_input_index=float(json['destinationInputIndex']) if json.get('destinationInputIndex') is not None else None,
        )


@event_class('WebAudio.nodesDisconnected')
@dataclass(slots=True)
class NodesDisconnected:
    '''Notifies that AudioNodes are disconnected. The destination can be null, and it means all the outgoing connections from the source are disconnected.'''
    context_id: GraphObjectId
    source_id: GraphObjectId
    destination_id: GraphObjectId
    #: *(Optional)*
    source_output_index: float | None = None
    #: *(Optional)*
    destination_input_index: float | None = None

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> NodesDisconnected:
        return cls(
            context_id=GraphObjectId.from_json(json['contextId']),
            source_id=GraphObjectId.from_json(json['sourceId']),
            destination_id=GraphObjectId.from_json(json['destinationId']),
            source_output_index=float(json['sourceOutputIndex']) if json.get('sourceOutputIndex') is not None else None,
            destination_input_index=float(json['destinationInputIndex']) if json.get('destinationInputIndex') is not None else None,
        )


@event_class('WebAudio.nodeParamConnected')
@dataclass(slots=True)
class NodeParamConnected:
    '''Notifies that an AudioNode is connected to an AudioParam.'''
    context_id: GraphObjectId
    source_id: GraphObjectId
    destination_id: GraphObjectId
    #: *(Optional)*
    source_output_index: float | None = None

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> NodeParamConnected:
        return cls(
            context_id=GraphObjectId.from_json(json['contextId']),
            source_id=GraphObjectId.from_json(json['sourceId']),
            destination_id=GraphObjectId.from_json(json['destinationId']),
            source_output_index=float(json['sourceOutputIndex']) if json.get('sourceOutputIndex') is not None else None,
        )


@event_class('WebAudio.nodeParamDisconnected')
@dataclass(slots=True)
class NodeParamDisconnected:
    '''Notifies that an AudioNode is disconnected to an AudioParam.'''
    context_id: GraphObjectId
    source_id: GraphObjectId
    destination_id: GraphObjectId
    #: *(Optional)*
    source_output_index: float | None = None

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> NodeParamDisconnected:
        return cls(
            context_id=GraphObjectId.from_json(json['contextId']),
            source_id=GraphObjectId.from_json(json['sourceId']),
            destination_id=GraphObjectId.from_json(json['destinationId']),
            source_output_index=float(json['sourceOutputIndex']) if json.get('sourceOutputIndex') is not None else None,
        )
